### ISSUE TITLE
constructor_as_function and std::initializer_list

### ISSUE THREAD

**Issue by theodelrieu** [Dobiasd/FunctionalPlus#101]
Hi, I think there is a problem with the implementation of `constructor_as_function`.

```cpp
return T{args...};
```

IIRC, `make_unique` uses parenthesis instead of curly braces, I believe we should do the same.

Here is the current behavior:

```cpp
struct Test {
  Test(int, int){} // 1
  Test(std::initializer_list<int>){} // 2
};

fplus::constructor_as_function<Test>(4, 2); // will call constructor 2
```

**Comment by Dobiasd** [comment]
Good catch!
