### ISSUE TITLE
Clean-up: default template arguments

### ISSUE THREAD

**Issue by theodelrieu** [Dobiasd/FunctionalPlus#105]
There's a lot of defaulted template arguments in the library, they are primarily used to deduce function return types.

The problem is that one can accidentally replace them, and they make the search API less clear.

Most can be removed thanks to C++14's return type deduction.
However, it seems that a few are designed to be replaced? If so, making a list would greatly help to remove the unneeded ones.

**Comment by Dobiasd** [comment]
I think every template parameter can be removed where possible, except for `ContainerOut` in the following function templates: `convert_container`, `convert_container_and_elems`, `generate`, `generate_by_idx`, `maybe_to_seq`, `singleton_seq`, `numbers` and `numbers_step`.

**Comment by theodelrieu** [comment]
Ok, too bad you have to provide each template argument (e.g. in `singleton_seq`), but I don't see how we could avoid that.
