### ISSUE TITLE
Clean-up: remove result_of occurences

### ISSUE THREAD

**Issue by theodelrieu** [Dobiasd/FunctionalPlus#106]
`result_of` is deprecated in C++17, and has a lot of caveats.

We should use `invoke_result_t` instead. Note that `invoke_result_t` returns a `T&&` (as `std::declval`).

It is important to be careful when storing it into a template type:

```cpp
using Result = detail::invoke_result_t<F>;
// std::vector<T&&> will fail to compile
// using ContainerOut = std::vector<Result>;
using ContainerOut = std::vector<std::decay_t<Result>>;
```

**Comment by theodelrieu** [comment]
I'm on this one

**Comment by Dobiasd** [comment]
Do we need to dispatch to `result_of` if the compiler uses C++14 instead of  C++17?

**Comment by theodelrieu** [comment]
I don't see why that would be needed, `detail::invoke` works in C++11/14/17

**Comment by Dobiasd** [comment]
Sorry, I confused it with `std::invoke_result`.
