### ISSUE TITLE
Clean-up: merge namespaces detail && internal

### ISSUE THREAD

**Issue by theodelrieu** [Dobiasd/FunctionalPlus#108]
Renaming `detail` to `internal` is the first step. There are a few internal methods that are superseded by those in `detail`.

There's also some `static_assert` that do not use the `detail::trigger_static_assert` facility.

**Comment by Dobiasd** [comment]
Wow, that was quite a ride for me. :) But I learned a lot about the code you contributed.

Also the clean-up was really fruitful, since many now obsolete things (e.g. the whole `check_callable` facility from `compare.hpp) were removed.
