### ISSUE TITLE
clang 5 installation on travis fails

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#111]
https://api.travis-ci.org/jobs/285710163/log.txt?deansi=true
```
Err:3 http://apt.llvm.org/trusty llvm-toolchain-trusty-5.0/main amd64 libllvm5.0 amd64 1:5.0~svn315198-1~exp1
  404  Not Found
```

I hope this is caused by a mistake of the llvm people and we just have to wait. ;)

**Comment by offa** [comment]
LLVM has some problems at the moment. APT Repository was down for a while and the website, bugtracker etc. too.

**Comment by Dobiasd** [comment]
Ah coo, thanks for the info. :+1:

**Comment by Dobiasd** [comment]
It's working again.
