### ISSUE TITLE
[question] Generated files when building

### ISSUE THREAD

**Issue by danimtb** [Dobiasd/FunctionalPlus#117]
Hi,

I have seen that in order to use this library you have to generate some files with CMake.
In my case they were two files: `curry_instances.autogenerated_defines` and `fwd_instances.autogenerated_defines`.

I would like to know if those generated files may be different depending on the operating system, compiler used or not.

Thank you

**Comment by Dobiasd** [comment]
Hi Daniel,

you don't have to generate these two files. They are included in the repo and are the same for every compiler and operating system.

They are generated by me before I commit a change using `generate/generate_derived_functions.sh`. ;-)

So you can simply treat them like every other normal header file of the library too.

Tobias
