### ISSUE TITLE
Function adjacent_pairs crashes in MSVC2017 Debug mode

### ISSUE THREAD

**Issue by CrikeeIP** [Dobiasd/FunctionalPlus#119]
Hi =) adjacent_pairs advances iterator it2 beyond xs.end(), which crashes in debug mode on MSVC 2017 (V 15.2).
```
#include "fplus/fplus.hpp"
int main() {
	std::vector<int> vec = {1, 2, 4, 5 };
	auto x = fplus::adjacent_pairs(vec);
}
```
Proposal for a fix: [PR](https://github.com/Dobiasd/FunctionalPlus/commit/f6b4035a46025b01208fb6f01ceaf3606f2102be)

**Comment by Dobiasd** [comment]
Oh, good catch! Thanks a lot. :)
