### ISSUE TITLE
Issue tracker link in Bintray

### ISSUE THREAD

**Issue by danimtb** [Dobiasd/FunctionalPlus#120]
Hi @Dobiasd !

I forgot to tell you to change the issue tracker link in Bintray https://bintray.com/dobiasd/public-conan/functionalplus%3Adobiasd as it is pointing to the old conan-community repo.

And just to let you know, I have also deleted my packages of FuntionalPlus from conan-community and accepted your inclusion request to conan-center :)

**Comment by Dobiasd** [comment]
Oops, I blindly copy-pasted it over. I should have noticed it. Just corrected it. Thanks for all the babysitting. :D
