### ISSUE TITLE
fplus::map_union fails to compile for std::unordered_map

### ISSUE THREAD

**Issue by wbthomason** [Dobiasd/FunctionalPlus#127]
## Example code
```c++
#include "fplus/fplus.hpp"
#include <unordered_map>

int main(void) {
   std::unordered_map<int, int> foo = fplus::map_union(std::unordered_map<int, int>(), std::unordered_map<int, int>());
   return 0;
}
```
## Observed behavior
Compile error:
```
error: could not convert ‘fplus::map_union_with(F, const MapIn&, const MapIn&) [with F = fplus::map_union(const MapType&, const MapType&) [with MapType = std::unordered_map<int, int>]::<lambda(const Value&, const Value&)>; MapIn = std::unordered_map<int, int>]((* & dict1), (* & dict2))’ from ‘std::map<int, int, std::less<int>, std::allocator<std::pair<const int, int> > >’ to ‘std::unordered_map<int, int>’
     return map_union_with(get_first, dict1, dict2);
```
## Expected behavior
Code compiles.
## Cause?

I'm not sure why this happens, but it seems to have to do with the `SameMapTypeNewTypes` template https://github.com/Dobiasd/FunctionalPlus/blob/4b544e26e1c3e591efd06d22ac8bbc17c4a2b056/include/fplus/container_traits.hpp#L65 as used in https://github.com/Dobiasd/FunctionalPlus/blob/4b544e26e1c3e591efd06d22ac8bbc17c4a2b056/include/fplus/maps.hpp#L75. 

## System
I'm using Arch Linux with GCC 8.1.0 and `fplus` 0.2.1 (the latest release from `conan`).

I'm happy to help debug further! If I figure out what causes this, I'll submit a PR, but I'm not sure what it is yet...

**Comment by Dobiasd** [comment]
Oh, good catch. Thanks for the nice report.
I'll look into in a few days. However of course if you have an idea, I'm happy to receive your PR. ;-)

**Comment by Dobiasd** [comment]
The problem was `pairs_to_map_grouped` returned an `std::map` instead of an `std::unordered_map` in that case. With the [fix](https://github.com/Dobiasd/FunctionalPlus/commit/6480d368ee808c4a75c0bf2ae54da7e0e68a469e) `map_union`/`map_union_with` works for both kinds of dictionaries.

**Comment by wbthomason** [comment]
Ah, gotcha. Thank you!
