### ISSUE TITLE
Clang 6.0 on travis:   The C++ compiler "/usr/bin/clang++-6.0" is not able to compile a simple test program.

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#129]
https://travis-ci.org/Dobiasd/FunctionalPlus/jobs/389830560

https://api.travis-ci.org/v3/job/389830560/log.txt

It was working fine 6 days ago when I made the last commit. I only broke when I just triggered a rebuild.

**Comment by offa** [comment]
Strange, according to the log, libc++ wasn't found:

>   /usr/bin/ld: cannot find -lc++

**Comment by offa** [comment]
@Dobiasd i'm working on a solution …

**Comment by Dobiasd** [comment]
You are my hero! :metal:
