### ISSUE TITLE
could not deduce template argument for 'ContainerOut'

### ISSUE THREAD

**Issue by mruki** [Dobiasd/FunctionalPlus#132]
Hi,

I have just started playing with FunctionalPlus using Microsoft Visual Studio 2015 and have this stupid building error that I've been fighting with all day:

`1>  fplus_tutorial.cpp
1>.......\include\fplus\container_common.hpp(1166): error C2783: 'ContainerOut fplus::transform(F,ContainerIn &&)': could not deduce template argument for 'ContainerOut'`

is that something known? I've been googling a lot and checking everything on my side, but it just look like that code can't be really handled by VS15.

Many thanks in advance for help.

BR,
Konrad

**Comment by mruki** [comment]
Hey Tobias,

Thanks for replying. The code is really simple - it's just a snippet from the readme file#include "stdafx.h"

`#include <fplus/fplus.hpp>
#include <iostream>

int main()
{
	std::list<std::string> things = { "same old", "same old" };
	if (fplus::all_the_same(things))
		std::cout << "All things being equal." << std::endl;
}:`

As said - I just started with this - I think the problem lies in the VS15 compiler somehow, but then again you said it should be fine there, which is weird.

**Comment by Dobiasd** [comment]
Do you have C++14 support of your compiler enabled for your project?

I don't have Visual Studio 2015 here, so I only tried with gcc, but it works:

```cpp
// fplus_issue_132.cpp
#include <fplus/fplus.hpp>
#include <iostream>
int main()
{
    std::list<std::string> things = { "same old", "same old" };
    if (fplus::all_the_same(things))
        std::cout << "All things being equal." << std::endl;
}
```

```
$ g++ -std=c++14 fplus_issue_132.cpp -o fplus_issue_132
$ ./fplus_issue_132
All things being equal.
```

I only removed `#include "stdafx.h"` and of course the `:` at the end of your code. :wink:

Please check the C++14-flag and also if there are any updates available for your compiler that you need to install. Also please make sure you are really creating a C++ project and not some C++/CLI thing.

**Comment by mruki** [comment]
Colon was only present here of course :)
There is a flag (/std:c++14) for Visual C++ compiler, but only available since Update 3 of VS15.
I also read a bit after VS15's c++ and it turns out in earlier versions it only supported c++11 and some parts of c++14. Perhaps it's this Update 3 that gives the full standard.
I will try to get this update and let you know if it helps.

Thanks,
Konrad

**Comment by pthom** [comment]
On my side this code compiles perfectly with msvc 2015 Version 14.0.25341.01 update 3, either in 32 bits and 64 bits mode.

**Comment by mruki** [comment]
I have just installed VS15 Update 3 and the code compiles! So it was just a matter of getting c++14. Thanks so much for your assistance!
BR,
Konrad
