### ISSUE TITLE
Profiling decorator  ?

### ISSUE THREAD

**Issue by pthom** [Dobiasd/FunctionalPlus#133]
Hi,

I just discovered your library, and I like it very much. 

I am  also following your udemy course (https://www.udemy.com/functional-programming-using-cpp/) 
By the way, this course is so good that may be you should mention it in your main readme (it is currently somewhat hidden behind 2 links).

In this course, you explain how to profile a function, using - rather tedious - C++ code ;-)

This made me think that I would love to have a way to profile a function using fplus.

Below is the current status of what I thought (pardon me if my pseudo code is not clear, I am quite new to this :-): 

````haskell
-- Types
-- The Time type is a double, or whatever type 
-- which is able to store duration and can be casted to seconds
Time = double  
Timed A  = (A, Time)    -- a type A becomes (A, Time) when lifted to Timed
Nb_runs = Uint

-- Higher order functions
lift_timed : ( a.. -> b ) -> ( a.. -> Timed b ) -- a.. means a "tuple of types"
compose_timed : ((a.. -> Timed b), (b -> Timed c)) -> (a.. -> Timed c) 
-- Profiler
profile_function : ( a.. -> b ), a.., nb_runs -> double
````

I will probably try to implement something like this, but I am afraid of the template noise I might have to deal with... 
Did you try to implement something like this? Do you think it would make a good addition to fplus?

By the way, a huge thank for your frugally-deep library, it saved me a lot of time recently after a long battle where I fought successively with tensorflow, mxnet, opencv and pytorch. Fdeep proved to be the most production ready way to integrate my neural network into my project :-)

PS : 

I have some more thoughts on the profiling, but may be this is going too far, because this begins to take the role of a real profiler (and this is a dangerous road !). Anyway, here is the idea: 

````haskell

-- Types
FunctionName = string
AnnotatedTime = (FunctionName, Time)
AnnotatedTimes = [ AnnotatedTime ]
AnnotatedTimed A = (A, AnnotatedTime)
AnnotatedTimesSession A = ( AnnotatedTimes, A )

-- Higher order functions
lift_annotated_time : (( a.. -> b ), function_name) -> ( a.. -> AnnotatedTimed b )
compose_annotated_timed : ((a.. -> AnnotatedTime b), (b -> AnnotatedTime c)) -> (a.. -> AnnotatedTimesSession c)

-- Session analysis utility
TotalTime = Time
FunctionTimeSummary = ( FunctionName, Nb_runs, TotalTime, Time )
analyse_times: AnnotatedTimes -> [ FunctionTimeSummary ]
````

**Comment by Dobiasd** [comment]
Hi pthom,

first, thanks a lot for this positive feedback. I just [added a link to the course to `README.md`](https://github.com/Dobiasd/FunctionalPlus/commit/a0693027c988cf92d01c5bee86dbbbd7e60626e4). :slightly_smiling_face: 
And also awesome that frugally-deep is useful for you too.

So, now to your idea:
I really like it! `compose_timed` looks like a monadic bind for a new `Timed` type. Nice!
`lift_timed` just does not have the right name, I guess. `lift` is usually used for functor-like behavior, where you "lift" a normal function into the world of the functor, e.g., `lift_maybe : (a -> b) -> (Maybe a -> Maybe b)`. But I know what you mean with your function and what it is good for.

I did not yet think about implementing something like this yet, but if it's not too complicated to use, I would love to add it to the library. I suggest you start with the simple `( a.. -> b ) -> ( a.. -> Timed b )` function (however it will be named), with some unit tests. A PR would be nice (if you like) so I can follow the stuff and you have direct feedback from Travis.

For implementing the `Timed` type, you probably can look a bit into the [current implementation of the `Maybe` type and the corresponding functions](https://github.com/Dobiasd/FunctionalPlus/blob/master/include/fplus/maybe.hpp). However I can not yet foresee how terrible the template stuff will have to become for this. :wink:

**Comment by pthom** [comment]
Hi, 

I feel bad because I did not have time to work on this enough yet. I promise I will come back to it in the near future. 
Do not hesitate to temporarily close this issue if you wish, I will post updates to it when I am ready to work on it. 


PS:
On a side note, I just learned about a library named `argot` which might be of interest to you, since it has to do with `std::invoke` (and its cousins `std::apply` and `std::visit` which is heavily used by fplus). 

This is just food for thought (if you are interested) :-) and I do not know the author, except that he seems to developing this as a possible future boost library.

Here is a quick summary of what I understood (this is just based on the video I viewed)

````cpp
// Say you have a variadic print function
auto print = (auto & stream, auto const... & args) { /*...*/ }

// And you want to use it on tuples, variants
std::tuple<int, float, char> tup = /*...*/
std::variant<int, float, char> var = /*...*/

// For a tuple you need to use std::apply
std::apply([](auto const& ... args) { print(std::cout, args...); }, tup );
// And for a variant you need to use std::visit
std::visit([](const auto & arg) { print(std::cout, arg); }, var );

// With argot, you can use argot::call in both cases
// prov::unpack stands for ArgumentProvider::unpack
argot::call(print, argot::prov::unpack(tup)); 
// prov::alternative_of stands for ArgumentProvider::select_alterrnative
argot::call(print, std::cout, argot::prov::alternative_of(var)); 

// And you can also turn your print function into another function 
// that will do the unpack / alternative_of / extract_maybe / ...
// The '+' operator can unpack tuples, select the correct variant type for std::variant
// as well as maybe types
auto print2 = argot::as_call_object(print);
print2(std::cout, +tup2); 

// He has a similar approach for futures, but it is more involved
````

Anyway, if you are interested, here are the links:
Video : https://www.youtube.com/watch?v=pKVCB_Bzalk
Git repo : https://github.com/mattcalabrese/argot

**Comment by Dobiasd** [comment]
Don't worry. We have time (sorry for the pun) to implement this new feature. 

Thanks. I'll have a look at this library. Sounds interesting.

**Comment by Dobiasd** [comment]
In [PR140](https://github.com/Dobiasd/FunctionalPlus/pull/140) we talked about dropping the type-theory-heavy approach discussed here for the simpler one, that was merged meanwhile.

So I'll close this issue for now. We can re-open it in case we'd like to re-visit the initial idea.
