### ISSUE TITLE
Question about zip_with implementation

### ISSUE THREAD

**Issue by wbthomason** [Dobiasd/FunctionalPlus#139]
First off, thank you (again) for such a wonderful library!

I recently ran into some unexpected behavior with `zip_with` while trying to zip a `std::vector<std::string>` with a `std::list<std::string>`. It seems that `zip_with` requires that both containers have the same container type (the static assertion at lines 42-46 of pairs.hpp). I was wondering why this restriction is in place, as I didn't see anything in the implementation of `zip_with` that depended on the containers being the same, just on them having the standard container interface.

Thanks for the help!

**Comment by Dobiasd** [comment]
Hi Wil,

you are right. The restriction does not seem to make sense. So I removed it, and added a test covering this use case.
