### ISSUE TITLE
Review the std library problem on OS X

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#147]
On Mac OS it's necessary to explicitly add *libstdc++* and *libm* (see #146). This is now [forced](
https://github.com/Dobiasd/FunctionalPlus/blob/e813ab2d791c2cefb057723ed0da9943325b8683/test/CMakeLists.txt#L14) for all Unix like builds.

@pthom Are you building with GCC on Mac OS?

**Comment by pthom** [comment]
I am building with "Apple Clang" (apple fork of clang) and a separate install of clang. 

No gcc though.

I will see if I have time to add an OSX builder to the travis matrix.  It should not be to complicated.

**Comment by offa** [comment]
This is odd, clang should pick up libc++ by default on your system. What error do you get if you build without the workaround (withouth [this line](https://github.com/Dobiasd/FunctionalPlus/blob/master/test/CMakeLists.txt#L14))?

**Comment by pthom** [comment]
Well the problem I encounter seems not to be apple specific.

Sorry if this message is a bit long, but I wanted to make a full analysis.

### Status with "apple clang" : works 

The compilation will work even if I build without the workaround.

````bash
mkdir build-appleclang && cd build-appleclang
conan install .. -obuild_unittest=True && cmake .. -DFPLUS_BUILD_UNITTEST=ON -DFPLUS_UNITTEST_USE_CONAN=ON
make
````

### Status with clang7 under osx 

The compilation will not work without the workaround.

````bash
brew install llvm # will install clang7 into /usr/local/Cellar/llvm/7.0.0/bin
mkdir build-clang7 && cd build-clang7
export CC=/usr/local/Cellar/llvm/7.0.0/bin/clang
export CXX=/usr/local/Cellar/llvm/7.0.0/bin/clang
# export CXXFLAGS="-stdlib=libc++"
conan install .. -obuild_unittest=True && cmake .. -DFPLUS_BUILD_UNITTEST=ON -DFPLUS_UNITTEST_USE_CONAN=ON
make

Undefined symbols for architecture x86_64:
  "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const", referenced from:
      doctest::detail::logTestStart(doctest::detail::TestCase const&) in stringtools_cp1251_test.cpp.o
etc...
````


### Status with clang7 under ubuntu 16.04 / docker

As I was curious about the clang 7 issue, I tried to compile inside a docker container (based on ubuntu 16.04). 
I tried to follow the exact same instructions as in the `.travis.yml` file, with no success.

Here is what I did:
_Docker Container creation_
````bash
docker run --name u16-clang7 -it ubuntu:16.04 /bin/bash
````

_Inside the docker container_
````bash
apt-get update && apt-get install -y build-essential git cmake curl wget python-pip nano vim

# cf https://apt.llvm.org/
echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main" >> /etc/apt/sources.list
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
apt-get update
apt-get install -y clang-7 libc++-7-dev libc++abi-7-dev


cd /root/
git clone https://github.com/onqtam/doctest
(cd doctest && git checkout tags/1.2.9 && mkdir -p build && cd build && cmake .. && make && make install)

git clone https://github.com/Dobiasd/FunctionalPlus.git
export CC=clang-7
export CXX=clang-7
# export CXXFLAGS="-stdlib=libc++" # the link will fail with or without CXXFLAGS

cd FunctionalPlus && mkdir -p build && cd build
cmake .. -DFPLUS_BUILD_UNITTEST=ON

# sans CXXFLAGS
make
[  1%] Linking CXX executable udemy_course_test
CMakeFiles/udemy_course_test.dir/udemy_course_test.cpp.o: In function `doctest::detail::rawMemoryToString(void const*, unsigned int)':
udemy_course_test.cpp:(.text+0x17b): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)'
udemy_course_test.cpp:(.text+0x18c): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'

````

However, if I enable the workaround in `test/CMakeList.txt` (i.e I enable it whatever the plaform), then the compilation succeeds.


### What to do ?

As a matter of fact the compilation works correctly under OSX with the standard compiler. The issue I encounter is more specific to clang-7. 

So, the workaround can be suppressed IMHO. 

However, I would be interested in your opinion about what I did wrong when trying to compile under docker/ubuntu:16.04

**Comment by offa** [comment]
Thanks for your testing!

> **Status with "apple clang" : works**
> The compilation will work even if I build without the workaround.

:+1: 

> **Status with clang7 under osx**
> The compilation will not work without the workaround.

This sounds like a clang7 integration issue. As noted earlier, clang should pickup it' standard library by default.

> **Status with clang7 under ubuntu 16.04 / docker**
> As I was curious about the clang 7 issue, I tried to compile inside a docker container (based on ubuntu 16.04).

For whatever reason the default installed GCC (5.4) is picked up  instead of clang, when building doctest.

`CXX` should be set to **`clang++`** (or `clang++-7` on Ubuntu) – it is set to just `clang` in OS X (non-apple) and Ubuntu.

> As a matter of fact the compilation works correctly under OSX with the standard compiler. The issue I encounter is more specific to clang-7.

Clang 7 is working on linux (maybe some configuration problems on Ubuntu 16.04 listed above?). Travis builds use 14.04 LTS but the same packages as 16.04, so I don't expect all Ubuntus to be broken.


> So, the workaround can be suppressed IMHO.

:+1:  That's fine, I'm going to clean that up.

**Comment by pthom** [comment]
Many thanks for your answer, your script also works on my side 👍 

Some side notes: 
- Setting CXX before compiling doctest is a good idea. However, as doctest is a header only library, this will not make any change

> setting CXX to clang++-7

My bad...

> export CXXFLAGS="-stdlib=libc++"

Actually, the compilation now succeeds under the docker container with or without this flag.

**Comment by offa** [comment]
> However, as doctest is a header only library, this will not make any change

Indeed, this makes sense.
