### ISSUE TITLE
AppVeyor builds (MSVC 2017) fail with C4643

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#152]
https://ci.appveyor.com/project/Dobiasd/functionalplus/build/job/n896fph5y7739a86
```
C:\projects\doctest\examples\all_features\..\..\doctest\doctest.h(544): error C2220: warning treated as error - no 'object' file generated [C:\projects\doctest\build\examples\all_features\all_features.vcxproj]
C:\projects\doctest\examples\all_features\..\..\doctest\doctest.h(544): warning C4643: Forward declaring 'char_traits' in namespace std is not permitted by the C++ Standard. 
```

@pthom I tried to silence the warning with
```cpp
__pragma(warning(disable:4643))
```
and with an addition to `cmake/toolchain_msvc.cmake`, but both approaches did not fix it.

Do you have an idea?

**Comment by Dobiasd** [comment]
Updating `doctest` probably would also help. I tried, but failed, so I opened [an issue](https://github.com/onqtam/doctest/issues/189).

**Comment by pthom** [comment]
Hi,
I will have a look at it. You are right, the issue is inside doctest, since with this version (1.2.9), the initial build of doctest fails. This is what is mentioned in the appveyor logs.

**Comment by Dobiasd** [comment]
> the initial build of doctest fails.

Haha, thanks for the remark. I somehow tried to ignore this warning the FunctionalPlus test code around `#include "doctest.h"`. No wonder this did not help. :roll_eyes: :grin:

I'm now trying to upgrade doctest.

**Comment by Dobiasd** [comment]
The latest doctest version still had some problems with MSVC:

```
warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
```

```
warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
```

But disabling building its tests helped.

So now everything is working again. :)
