### ISSUE TITLE
Use with non-STL containers

### ISSUE THREAD

**Issue by wbthomason** [Dobiasd/FunctionalPlus#153]
Just to confirm, FunctionalPlus only works with STL containers, correct?

I'm trying to swap out the hash map used in my code for performance from `std::unordered_map` to a third-party implementation that claims to be a drop-in replacement, and get a lot of compile errors from FP. Looking at some of the code (e.g. in `maps.hpp`), it seems that the library pretty heavily relies on STL containers explicitly. Is that correct?

Also, please note that I'm not asking for this to change - I just want to gauge how much work would be required to use this alternative map implementation, and if that work involves removing FP from my codebase, it changes the cost significantly.

Thanks!

**Comment by Dobiasd** [comment]
So far I only tested it with some trivial cases like `transform`ing a custom `vector`. But even that was some time ago.

Fow the hash-map case

**Comment by Dobiasd** [comment]
Is your custom hashmap freely available, so I can reproduce the problem?
Maybe it suffices to implement some traits for it in the user's part of the code.

**Comment by wbthomason** [comment]
I was trying to use https://github.com/greg7mdp/sparsepp. I can extract a summary of the compile errors I get tomorrow and post it here, if that would help.

Thank you for providing this great library in the first place - it's been a huge help to me.

**Comment by Dobiasd** [comment]
Currently I'm afk, but if you post a minimal example reproducing the error, I can look into it next week.

**Comment by wbthomason** [comment]
I'll have time to construct a minimal example in a few days, but: I've just tried using https://github.com/Tessil/hopscotch-map instead, and it seems to succeed (at least with `fplus::map_contains`; I haven't tried other FP functions with it). As far as I'm concerned, that's enough to warrant closing this issue - feel free to re-open if you'd still like a minimal example/more testing with third-party structures.

**Comment by Dobiasd** [comment]
Ah, cool.

To me personally my motivation to nonetheless continue with this issue depends. Is your problem solved now, i.e., are you now just using the hopscotch map instead of the sparsepp one? If so, great. But if you are still blocked on your actual project, I'd like to check if the situation can be improved. :)

**Comment by wbthomason** [comment]
My problem is solved, but I'd be happy to continue with the issue if it would help.

I did a bit more testing and found that the hopscotch map, at least, can be dropped in many places with FP. It did cause errors with `fplus::swap_keys_and_values`. I'll report any more functions that break here as I continue to use it.
