### ISSUE TITLE
Plans for C++17?

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#169]
General question: How is the future about C++17?

**Comment by Dobiasd** [comment]
If using it helps us solve some pressing problem, sure, let's consider it. If not, I guess keeping C++14 compatibility is still also a nice thing to have.

Do you have something special in mind?

**Comment by offa** [comment]
No problems so far, even with C++17. More a question of interest, as I start using (upcoming) C++20.

**Comment by Dobiasd** [comment]
I mean, if the C++ committee continues to adhere to backward compatibility, even without any change FunctionalPlus should work out-of-the-box even with a C++30 compiler in 10 years. :slightly_smiling_face:

**Comment by offa** [comment]
The only issue I met so far is the removal of `std::result_of_t` (deprecated in C++17). I haven't found a short overview of C++20's removed / deprecated api's, but [P0619](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0619r4.html) should contain them.

**Comment by offa** [comment]
> I mean, if the C++ committee continues to adhere to backward compatibility, 

I hope some day, they get rid some old stuff :laughing:

**Comment by Dobiasd** [comment]
For things, that can easily be replaced, like `std::result_of_t`, sure, that's possible. But I guess nothing major will ever be removed since the existing code bases are just too old, large and many.

Doing such things seems more like something for a younger language, like, e.g., Rust.

**Comment by offa** [comment]
I still hope for the end of preprocessor and macros :see_no_evil:

**Comment by Dobiasd** [comment]
Have fun rewriting [`composition.hpp`](https://github.com/Dobiasd/FunctionalPlus/blob/e306deecd519c2358b4f338c88b2bc269552c78a/include/fplus/composition.hpp#L344-L390). :stuck_out_tongue:

**Comment by offa** [comment]
Oh …
