### ISSUE TITLE
Error when compiling with GCC 10

### ISSUE THREAD

**Issue by ruanformigoni** [Dobiasd/FunctionalPlus#170]
Greetings,

When using GCC trunk, the code in `split.hpp` does not compile, here is the error output:

<details><summary>Error Output</summary>
/home/ruan/.conan/data/functionalplus/v0.2.6-p0/dobiasd/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/fplus/split.hpp: In instantiation of ‘ContainerOut fplus::split_by(UnaryPredicate, bool, const ContainerIn&) [with UnaryPredicate = bool (*)(const char&); ContainerIn = std::__cxx11::basic_string<char>; ContainerOut = std::vector<std::__cxx11::basic_string<char> >]’:
/home/ruan/.conan/data/functionalplus/v0.2.6-p0/dobiasd/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/fplus/string_tools.hpp:76:20:   required from ‘ContainerOut fplus::split_lines(bool, const String&) [with String = std::__cxx11::basic_string<char>; ContainerOut = std::vector<std::__cxx11::basic_string<char> >]’
/home/ruan/.conan/data/functionalplus/v0.2.6-p0/dobiasd/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/fplus/side_effects.hpp:428:76:   required from here
/home/ruan/.conan/data/functionalplus/v0.2.6-p0/dobiasd/stable/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/fplus/split.hpp:342:20: error: ambiguous overload for ‘operator=’ (operand types are ‘std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >’ and ‘<brace-enclosed initializer list>’)
  342 |             *itOut = {};
      |             ~~~~~~~^~~~
In file included from /home/ruan/GCC/include/c++/10.0.1/iterator:63,
                 from /home/ruan/.conan/data/fmt/6.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/include/fmt/core.h:13,
                 from /home/ruan/.conan/data/fmt/6.1.2/_/_/package/b173bbda18164d49a449ffadc1c9e817f49e819d/include/fmt/format.h:36,
                 from /home/ruan/Mega/papers-authored/An automated routing approach for NML circuits/code/src/main.cpp:9:
/home/ruan/GCC/include/c++/10.0.1/bits/stl_iterator.h:847:7: note: candidate: ‘constexpr std::insert_iterator<_Container>& std::insert_iterator<_Container>::operator=(const typename _Container::value_type&) [with _Container = std::vector<std::__cxx11::basic_string<char> >; typename _Container::value_type = std::__cxx11::basic_string<char>]’
  847 |       operator=(const typename _Container::value_type& __value)
      |       ^~~~~~~~
/home/ruan/GCC/include/c++/10.0.1/bits/stl_iterator.h:856:7: note: candidate: ‘constexpr std::insert_iterator<_Container>& std::insert_iterator<_Container>::operator=(typename _Container::value_type&&) [with _Container = std::vector<std::__cxx11::basic_string<char> >; typename _Container::value_type = std::__cxx11::basic_string<char>]’
  856 |       operator=(typename _Container::value_type&& __value)
      |       ^~~~~~~~
/home/ruan/GCC/include/c++/10.0.1/bits/stl_iterator.h:778:11: note: candidate: ‘constexpr std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >& std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >::operator=(const std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >&)’
  778 |     class insert_iterator
      |           ^~~~~~~~~~~~~~~
/home/ruan/GCC/include/c++/10.0.1/bits/stl_iterator.h:778:11: note: candidate: ‘constexpr std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >& std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >::operator=(std::insert_iterator<std::vector<std::__cxx11::basic_string<char> > >&&)’
make[2]: *** [src/CMakeFiles/main.dir/build.make:80: src/CMakeFiles/main.dir/main.cpp.o] Error 1
make[2]: Leaving directory '/home/ruan/Mega/papers-authored/An automated routing approach for NML circuits/code/build'
make[1]: *** [CMakeFiles/Makefile2:111: src/CMakeFiles/main.dir/all] Error 2
make[1]: Leaving directory '/home/ruan/Mega/papers-authored/An automated routing approach for NML circuits/code/build'
make: *** [Makefile:101: all] Error 2
fish returned exit code 2
</details>

I have fixed the issue with the following modification:
```diff
-  *itOut = {};
+  *itOut = std::insert_iterator<ContainerOut>{};
```

I have created a pull request #171.

**Comment by Dobiasd** [comment]
Fixed with [PR 171](https://github.com/Dobiasd/FunctionalPlus/pull/171).
