### ISSUE TITLE
In conan-center, provide CMake targets if possible

### ISSUE THREAD

**Issue by ruanformigoni** [Dobiasd/FunctionalPlus#175]
Greetings,

This issue is a CMake request to enable `find_package`, for the conan-center releases. Currently, this is not possible:

```cmake

if(NOT FunctionalPlus_FOUND)
  find_package(FunctionalPlus REQUIRED)
endif()

target_link_libraries(mylib FunctionalPlus::fplus Catch2::Catch2)
```

I've change conanfile.py to adhere these requests, in my [bintray](https://bintray.com/beta/#/ruanformigoni/functionalplus/functionalplus:ruanformigoni?tab=overview), and it worked with some simple changes. Furthermore, created a pull request #176.

**Comment by Dobiasd** [comment]
Fixed with [pull/176](https://github.com/Dobiasd/FunctionalPlus/pull/176).
