### ISSUE TITLE
map_keep and map_keep_values as forwarding references

### ISSUE THREAD

**Issue by ruanformigoni** [Dobiasd/FunctionalPlus#177]
Current behaviour / Use case:
```cpp
template<typename T>
template<typename U>
std::vector<T> Graph<T>::predecessors(U u) const noexcept
{
  std::vector<U> tmp{u};
  return fp::get_map_keys(fp::map_keep_values(tmp,*g));
}
```

Desired behaviour accepts rvalues:
```cpp
template<typename T>
template<typename U>
std::vector<T> Graph<T>::predecessors(U u) const noexcept
{
  return fp::get_map_keys(fp::map_keep_values(std::vector<U>{u},*g));
}
```
---
This would require a change in the interface from:
```cpp
template <typename MapType, typename KeyContainer>
MapType map_keep(const KeyContainer& keys, const MapType& map)
```
```cpp
template <typename MapType, typename ValueContainer>
MapType map_keep_values(const ValueContainer& values, const MapType& map)
```
to:
```cpp
template <typename MapType, typename KeyContainer>
MapType map_keep(KeyContainer&& keys, const MapType& map)
```
```cpp
template <typename MapType, typename ValueContainer>
MapType map_keep_values(ValueContainer&& values, const MapType& map)
```

**Comment by Dobiasd** [comment]
Looks reasonable. :+1: Also, it seems it won't break most of the existing client code, already using the functions (except maybe some rare cases where somebody is using the exact function signature to obtain a pointer to it or similar).

Would you like to give the implementation a try in a PR? Otherwise I could start working on it in about two weeks (I'm afk till then).

**Comment by ruanformigoni** [comment]
> Looks reasonable. +1 Also, it seems it won't break most of the existing client code, already using the functions (except maybe some rare cases where somebody is using the exact function signature to obtain a pointer to it or similar).
> 
> Would you like to give the implementation a try in a PR? Otherwise I could start working on it in about two weeks (I'm afk till then).

Of course, I'll work on it! :+1:

**Comment by Dobiasd** [comment]
Thanks for the PR. I'm not sure if I've already understood the issue correctly. The current (old) implementation already accepts r-values, i.e., your initial example (`return fp::get_map_keys(fp::map_keep_values(std::vector<U>{u},*g));`) should already work, even without the change, or am I missing something?

**Comment by ruanformigoni** [comment]
> Thanks for the PR. I'm not sure if I've already understood the issue correctly. The current (old) implementation already accepts r-values, i.e., your initial example (`return fp::get_map_keys(fp::map_keep_values(std::vector<U>{u},*g));`) should already work, even without the change, or am I missing something?

You're right, after some digging, it was an issue on my end. Closing this issue and PR, sorry about that.

**Comment by Dobiasd** [comment]
No problem. Partially my fault too, since I misunderstood the issue initially, incorrectly assuming it was about re-using some instances of the provided container, which does not even make sense in that case. :-)
