### ISSUE TITLE
Conanfile.txt issue

### ISSUE THREAD

**Issue by YannickLecroart** [Dobiasd/FunctionalPlus#182]
Hi Tobias,

You need to remove the uppercase letter in your conan text file (installation section). 

[requires]
functionalplus/v0.2.9-p0@Dobiasd/stable

[generators]
cmake

So functionalplus/v0.2.9-p0@dobiasd/stable instead of functionalplus/v0.2.9-p0@Dobiasd/stable

Otherwise, we get the following error while trying to install the package with Conan. 

![fp](https://user-images.githubusercontent.com/43994829/92573500-2a73e800-f286-11ea-80c6-310884015924.jpg)

Regards,

**Comment by Dobiasd** [comment]
I wish I had created my GitHub username and all repositories lower-case only. :grimacing:

Thanks a lot for the remark, [it's fixed now](https://github.com/Dobiasd/FunctionalPlus/commit/9f2d88a9b94d3b35e61bc5d41f2d37c209ceec5f). :slightly_smiling_face:
