### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by jchia** [Dobiasd/FunctionalPlus#184]
How is the user supposed to use fplus? Is including fplus/fplus.hpp the only way? Can he include other non-internal headers instead? If so, what combinations of other headers are allowed? This question is necessary because currently, certain combinations break, e.g. just including fplus/maybe.hpp breaks but including fplus/container_common.hpp followed by fplus/maybe.hpp is fine. (Also see #183.) There are circular dependencies between the headers, so just adding includes until the compiler shuts up does not always work because the order of include matters.

If only fplus/fplus.hpp is supposed to be included, I think the README should say so clearly, especially because of the existence of the internal/ directory implying that non-internal things can be used. Including fplus/fplus.hpp is not cheap, though, and costs 0.5s more to compile on my machine than just including fplus/container_common.hpp (0.77s vs 0.27s) .

If other headers can also be included by the user instead of fplus/fplus.hpp, then I think the rules for including them should be specified in the README. All the examples in the README just include fplus/fplus.hpp.

**Comment by Dobiasd** [comment]
Hi @jchia,

thanks a lot. Of course, you're totally right. Ideally, it would be possible to include each header not in the `internal` directory in isolation. I'll check if it is feasible to achieve this state, and also try to get rid of the circular includes.

If this is not possible, I'll adjust the `README.md` so that it explains, that including `fplus/fplus.hpp` is the only way.

**Comment by Dobiasd** [comment]
So, I've [fixed the includes](https://github.com/Dobiasd/FunctionalPlus/commit/4260e3915c0c15a578f6245bd1fe9b397993a255). :slightly_smiling_face:

Now every non-internal `.hpp` file can be included separately.

Also I've made sure no circular include dependencies are left, which I can be verified as follows:

```bash
cd include
echo "import networkx as nx" > detect_cycles.py
echo "edges = [" >> detect_cycles.py
grep -r . -e "#include" | perl -pe "s/^\.\///g" | perl -pe "s/.#include </,/g" | perl -pe "s/>$//g" | perl -pe "s/\//_/g" | perl -pe "s/\./_/g" | perl -pe "s/^/('/g" | perl -pe "s/,/','/g" | sed "s/$/'),/g" | grep -v autogenerated  >> detect_cycles.py
echo "]" >> detect_cycles.py
echo "cycles = list(nx.simple_cycles(nx.DiGraph(edges)))" >> detect_cycles.py
echo "if len(cycles) == 0:" >> detect_cycles.py
echo "    print('No include cycles found.')" >> detect_cycles.py
echo "else:" >> detect_cycles.py
echo "    print(len(cycles), 'cycles found:')" >> detect_cycles.py
echo "    for cycle in cycles:" >> detect_cycles.py
echo "        print(cycle)" >> detect_cycles.py
cat detect_cycles.py
echo "==="
python3 detect_cycles.py
rm detect_cycles.py
cd ..
```

The [generated `detect_cycles.py`](https://gist.github.com/Dobiasd/8a6d9db410354055317c2c592997644c) outputs `No include cycles found.`.

(I've checked that the script is working, by purposely introducing a circular dependency, and it was detected.)

@jchia Thanks again for this very good report. It helped to make the library better for everyone. :+1:
