### ISSUE TITLE
ends_with starts_with string helper functions

### ISSUE THREAD

**Issue by ferdymercury** [Dobiasd/FunctionalPlus#185]
It could be a nice addition if FPlus would have a function to check if a string starts or ends with a particular substring.

Maybe, there can be a preprocessor IF CXX standard == 20, use std::ends_with, otherwise, use fplus implementation.

```
/**
 * @brief Check if string ends with a given suffix
 * @param str the full string
 * @param suffix the end candidate
 * @return bool True if it ends with it
 * @see https://stackoverflow.com/questions/874134/find-out-if-string-ends-with-another-string-in-c
 */
bool ends_with(const std::string& str, const std::string& suffix);

/**
 * @brief Check if a string strats with a given prefix
 * @param str the full string
 * @param prefix the start candidate
 * @return bool True if it starts with it
 * @see https://stackoverflow.com/questions/874134/find-out-if-string-ends-with-another-string-in-c
 */
bool starts_with(const std::string& str, const std::string& prefix);

bool ends_with(const std::string& str, const std::string& suffix)
{
    return str.size() >= suffix.size() && 0 == str.compare(str.size()-suffix.size(), suffix.size(), suffix);
}

bool starts_with(const std::string& str, const std::string& prefix)
{
    return str.size() >= prefix.size() && 0 == str.compare(0, prefix.size(), prefix);
}

```

**Comment by Dobiasd** [comment]
`fplus::is_prefix_of` and `fplus::is_suffix_of` should already cover that. :slightly_smiling_face:

https://github.com/Dobiasd/FunctionalPlus/blob/f4cdc2fe5168b8ca749f4d3fbf87b04604db19ad/include/fplus/container_common.hpp#L1819-L1842

**Comment by ferdymercury** [comment]
Thanks for pointing out!

Would it be possible to have an overloaded function that accepts char*? (And converts them to string)

Otherwise, I get an error when doing:
fplus::is_suffix_of(".csv","myfilename.csv")

Maybe like this:

```
bool ends_with(const std::string& token, const std::string& xs)
{
    return is_suffix_of(token, xs);
}
```

**Comment by Dobiasd** [comment]
How writing this instead?

```cpp
fplus::is_suffix_of<std::string>(".csv", "myfilename.csv");
```

**Comment by ferdymercury** [comment]
That works, thanks. It forces me to write a bit more. The variant with ends_with I suggested is a bit more compact.

Otherwise, maybe something in this direction or template specialization could be doable:

```
template <unsigned short N1, unsigned short N2>
bool is_suffix_of(char token[N1], char xs[N2])
{
    return is_suffix_of<std::string>(token,xs);
}
```

**Comment by Dobiasd** [comment]
> It forces me though to write a bit more

Feel free to implement your `bool ends_with(const std::string& token, const std::string& xs)` in your code base as a tool. :wink: For FunctionalPlus it does not really fit the concept, because if we would provide a specialization for this, we would need to provide many other ones to in order to be consistent.

> maybe something in this direction or template specialization could be doable?

Currently, I don't feel too good about adding this specialization to the library either. I'd like to avoid treating `std::string` or char arrays/pointers (or `std::vector<std::pair<int, double>>` or whatever) in some special way.

**Comment by ferdymercury** [comment]
Ok, i understand, makes sense! Thanks for the support and for your nice library :)
