### ISSUE TITLE
"_MSC_VER" is not defined, evaluates to 0

### ISSUE THREAD

**Issue by jmaldon1** [Dobiasd/FunctionalPlus#195]
Using the `include_all_in_one` header. I am running into some GCC compilation errors.

```
error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
 3089 | #if _MSC_VER >= 1900
      |     ^~~~~~~~
compilation terminated due to -Wfatal-errors.
```

Compiling on Linux Ubuntu.

**Comment by Dobiasd** [comment]
Hi @jmaldon1,

thanks for the report.

I'm trying to reproduce the issue, but I fail to. I.e., using the all-in-one header with GCC works in my case.

Here is a minimal Docker example to reproduce my experience (`Dockerfile`):

```Dockerfile
FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y g++ wget

RUN wget https://raw.githubusercontent.com/Dobiasd/FunctionalPlus/5758d732c903046054c58473492717a091f57100/include_all_in_one/include/fplus/fplus.hpp

RUN echo '#include "fplus.hpp"' > main.cpp
RUN echo 'int main() {' >> main.cpp
RUN echo '    std::list<std::string> things = {"same old", "same old"};' >> main.cpp
RUN echo '    if (fplus::all_the_same(things))' >> main.cpp
RUN echo '        std::cout << "All things being equal." << std::endl;' >> main.cpp
RUN echo '}' >> main.cpp

RUN g++ --version
RUN g++ -std=c++14 main.cpp
RUN ./a.out
```

Relevant output:

```
Step 11/13 : RUN g++ --version

g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Step 12/13 : RUN g++ -std=c++14 main.cpp

Step 13/13 : RUN ./a.out

All things being equal.
```

Could you please give more information about your environment, or maybe even adjust the given `Dockerfile` to reproduce the error you see?

**Comment by jmaldon1** [comment]
Turns out I didn't check my compile args.

I have a big CMake project and it added `-Wundef` as one of the compile args. I removed that compile arg and it worked fine. 

Any reason you don't use this though?:

```c++
#if defined(_MSC_VER) && _MSC_VER >= 1900
```

**Comment by jmaldon1** [comment]
@Dobiasd  Seperate issue, but just wondering why there are no include guards or a `#pragma once`?

Was it just forgotten about?

**Comment by Dobiasd** [comment]
Oh, probably, yes. Thanks a lot for the remark.

@pthom Would you like to extend [`make_all_in_one.py`](https://github.com/Dobiasd/FunctionalPlus/blob/master/include_all_in_one/make_all_in_one.py) accordingly in a PR, i.e., let it add `#pragma once`? :slightly_smiling_face:
