### ISSUE TITLE
Is it compilable for avr?

### ISSUE THREAD

**Issue by zallesov** [Dobiasd/FunctionalPlus#2]
Have you tried to compile this code for Arduino like hardware? 
I'm failing on my first attempt . Looks like avr stl library is missing something that you need.
I'm a scala developer, and every time I write for(int i=0..... something small is dying in me.

**Comment by zallesov** [comment]
Already see that it is not. It uses c++14. and the compiler is kinda not there yet.

**Comment by Dobiasd** [comment]
You made me realize I only used very few C++14 features, and these were not really needed. So I just changed the code to solely need C++11. Please pull the new version, try again, and let me know if it works for you now.

**Comment by zallesov** [comment]
Sounds Promising. Did you try it on microcontrollers?
Will also try myself.

**Comment by Dobiasd** [comment]
A fully C++11-compatible compiler should be able to compile it, independent of the target platform.
But yeah, please try it out and let me know.
