### ISSUE TITLE
drop_if_with_idx() – what's wrong here?

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#20]
Here's an example where `keep_if_with_idx()` is Ok, but `drop_if_with_idx()` fails to compile:

### Predicate

```cpp
static bool accept_with_index(size_t index, int value)
{
    return ( index % 2 == 0 ) && ( value >= 10 );
}
```

### keep_if_with_idx() – Works

```cpp
const std::vector<int> v = { 1, 20, 30, 4, 50, 60, 7 };
auto result = fplus::keep_if_with_idx(accept_with_index, v);
// Result: { 30, 50 }
```

### drop_if_with_idx() – Fails to compile

```cpp
const std::vector<int> v = { 1, 20, 30, 4, 50, 60, 7 };
auto result = fplus::drop_if_with_idx(accept_with_index, v);
// Expected Result: { 1, 20, 4, 60, 7 }  --- Compilation fails
```

Compilation fails due a failed static assertions _("Wrong arity")_.

-------------------------------

Is there a mistake in the example / usage of `drop_if_with_idx()`?

**Comment by Dobiasd** [comment]
Oh, thanks for this perfect bug report. `drop_if_with_idx` was not yet covered by a test case. This is [fixed now](https://github.com/Dobiasd/FunctionalPlus/commit/33ce9c5295cb5813be803e549fac0feb649e7c86).
