### ISSUE TITLE
conan.io does not show latest version of FunctionalPlus and marks it as being deprecated/legacy

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#203]
On bintray.com, the latest versions of FunctionalPlus released to Conan (`0.2.13` and `0.2.12`) are shown: https://bintray.com/dobiasd/public-conan/functionalplus%3Adobiasd

conan.io, however, only shows the versions up to `0.2.10`: https://conan.io/center/functionalplus

Also, it tells the following:
```
Depreciation Notice: LEGACY PACKAGE
This package may no longer be supported.
```

![1bp66L6](https://i.imgur.com/1bp66L6.png)

@danimtb Did I do something wrong? (I don't see an error in the [upload to Conan in the CI of version `0.2.13`](https://travis-ci.org/github/Dobiasd/FunctionalPlus/jobs/747978815#L1186-L1206) and no big difference to [the past upload of version `0.2.10`](https://travis-ci.org/github/Dobiasd/FunctionalPlus/jobs/730195653).)

**Comment by Dobiasd** [comment]
Yay, it suddenly has the updated version! :tada:

![K2VrK2c](https://i.imgur.com/K2VrK2c.png)

The only thing that still confuses me is: Why is FunctionalPlus marked as legacy/deprecated?

**Comment by Dobiasd** [comment]
Yay, it suddenly stopped showing the deprecation notice. :tada:

![Z64IHp7](https://i.imgur.com/Z64IHp7.png)

The only weird thing now is that it does only show the first part of [the description](https://github.com/Dobiasd/FunctionalPlus/blob/e8285fbc8fe26f40627797e369acfa4c08eb9354/conanfile.py#L7), i.e., instead of

`Functional Programming Library for C++. Write concise and readable C++ code.`

it shows:

`Functional Programming Library for C++.`

But I guess I can live with that. `¯\_(ツ)_/¯`

**Comment by danimtb** [comment]
Hi @Dobiasd,

This is because Conan moved to a "centralized" recipe repository. This means that the community is taking care of creating and maintaining recipes for ConanCenter at https://github.com/conan-io/conan-center-index. This approach makes it easier to add new recipes without adding new files to the repository of the library and lowers the requirements to create packages. This is because the conan-center-index repo provides its own building service that generates the binary packages (or the header only one) automatically when a PR with a recipe is open. Once the PR is merged, packages are promoted to the ConanCenter repo and are publicly available.

Regarding the issues that you described above with bintray, this could be because the packages are synced in the background with ConanCenter (conan.io/center) and Bintray when recipes do not come from the conan-center-index repo, and that sync is not instantly done.

**Comment by Dobiasd** [comment]
@danimtb

Thanks a lot for the explanation. :slightly_smiling_face:
To make sure I understand correctly, do I need to do something for future releases of FunctionalPlus being handled correctly?

---

> Regarding the issues that you described above with bintray

`bintray.com` was working fine. All the issues I described above (not updating the version, showing a deprecation notice, showing only part of the `description`) were related to `conan.io`.

**Comment by danimtb** [comment]
It will be optimal to move the Conan recipe to conan-center-index so people can contribute fixes easily without "polluting" the functionalplus repo. This is also very convenient to decouple the source code from the packaging files.

For example, here you can see the author of the library ApprovalTests https://github.com/conan-io/conan-center-index/pull/3418 adding a new release version of the library. The recipe was initially contributed some time ago and now the author takes care of updating it with new version in this separated repo (in this case the author is taking care, but normally the users add the new versions if those are not available yet).

I believe it is quite an improvement and conan-center-index is experiencing a lot of engagement with library authors and recipe maintainers, contributing patches to the library repo to improve the build system or to the source code to make it more compatible for building the library in different systems/configurations.

So you can contribute the FunctionalPlus recipe following this how to: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md or instead, you can open a package request issue in the repo and eventually some contributors will take care of it 😄

**Comment by Dobiasd** [comment]
Not having the Conan stuff in this repo (especially the CI) sounds really good. I'll have a look into conan-center-index. :+1:

conda-forge automatically generates a pull request ([like this one](https://github.com/conda-forge/functionalplus-feedstock/pull/8)) every time I tag a new of FunctionalPlus, which I find extremely convenient. It is planned to add something similar to conan-center-index?

**Comment by danimtb** [comment]
don't have it handy right now but I believe there is an issue open to manage this via a github action or with some automation of releases monitored by the community

**Comment by Dobiasd** [comment]
For the record, FunctionalPlus was already added to conan-center-index:
https://github.com/conan-io/conan-center-index/pull/3864
:slightly_smiling_face:

**Comment by danimtb** [comment]
Oh wow! I was not aware of that. I told you that the community takes care ❤️ 
So at this point there is no need to maintain conan stuff in this repo as it can be consumed via `functionalplus/'0.2.13-p0`:

```
λ conan search functionalplus* -r conan-center
Existing package recipes:

functionalplus/v0.2-p1@dobiasd/stable
functionalplus/v0.2.1-p0@dobiasd/stable
functionalplus/v0.2.2-p0@dobiasd/stable
functionalplus/v0.2.3-p0@dobiasd/stable
functionalplus/v0.2.4-p0@dobiasd/stable
functionalplus/v0.2.5-p0@dobiasd/stable
functionalplus/v0.2.6-p0@dobiasd/stable
functionalplus/v0.2.7-p0@dobiasd/stable
functionalplus/v0.2.8-p0@dobiasd/stable
functionalplus/v0.2.9-p0@dobiasd/stable
functionalplus/v0.2.10-p0@dobiasd/stable
functionalplus/v0.2.12-p0@dobiasd/stable
functionalplus/v0.2.13-p0@dobiasd/stable
functionalplus/0.2.13-p0
```

Note that conan-center-index references do not have `<user>/<channel>`, to indicate it is coming from the central repo.

The last bit would be to automatically bump the version of the recipe in conan-center-index with every release, but as I said, the community would take care of it 😄
