### ISSUE TITLE
Lock doctest version

### ISSUE THREAD

**Issue by friendlyanon** [Dobiasd/FunctionalPlus#209]
I noticed that the testing in this library always happens using the latest doctest version, yet the required version in the test lists file is set to be 2.3.4  
This would prevent reproducible builds and I think it's just safer to pull in a known good version, as doctest doesn't make the promise that their master branch will always pass their CI.

This change could be included in https://github.com/Dobiasd/FunctionalPlus/pull/207

**Comment by Dobiasd** [comment]
Yeah, makes sense. We could also directly update to the most recent release of doctest, i.e., version `2.4.3`, if it works directly.
/cc @offa

**Comment by offa** [comment]
Indeed, I'll change the version in my PR. An update makes sense, but we should get things working before.

**Comment by offa** [comment]
@Dobiasd PR for update is on the way…

**Comment by Dobiasd** [comment]
Closed with https://github.com/Dobiasd/FunctionalPlus/pull/211
