### ISSUE TITLE
Clean install rules up?

### ISSUE THREAD

**Issue by friendlyanon** [Dobiasd/FunctionalPlus#220]
Considering my last sentence in https://github.com/Dobiasd/FunctionalPlus/pull/216#issue-547935166 I feel like that it should be mentioned that many things in the `install-rules.cmake` are remnants of a (not that good) template and I feel like the file should be reworked a bit.

I would remove some comments and variables that aren't really essential, inline the `${PROJECT_NAME}` dereferences (how often does a project change its name?), make code a little tighter, but still preserve the information in the form of comments to stay in the spirit of what I said in that PR.

This issue is to survey whether this change is desired or not.

**Comment by Dobiasd** [comment]
Sounds good to me. :+1:
