### ISSUE TITLE
implement drop_last_while method

### ISSUE THREAD

**Issue by ander335** [Dobiasd/FunctionalPlus#232]
Recently I had to write code like this:

// Note: fplus has no method drop_last_while
const auto p43 = fplus::reverse(p34);
const auto p43Without0 = fplus::drop_while([](string_view p) { return p == "0"; }, p43);
const auto p34Without0 = fplus::reverse(p43Without0);

With drop_last_while it would look better. Like:
const auto p34Without0 = fplus::drop_last_while([](string_view p) { return p == "0"; }, p34);

**Comment by Dobiasd** [comment]
Good idea. :+1:

We currently have:
- `drop`
- `drop_while`
- `drop_last`
- `take`
- `take_while`
- `take_last`

Introducing `drop_last_while` and `take_last_while` will make it complete. Are you interested in giving the implementation a try in a pull request?

**Comment by ander335** [comment]
Maybe a bit later
