### ISSUE TITLE
Unit tests always succeeding, even when breaking them on purpose

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#233]
While trying to implement something for [issues/232](https://github.com/Dobiasd/FunctionalPlus/issues/232) and test it locally, I ran into a strange effect. I've purposely implemented a broken test, but the test suite succeeded nonetheless. Here is a minimal example to reproduce the problem:

```Dockerfile
FROM ubuntu:20.10

# Set up OS
RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake git

# Install doctest
RUN git clone --depth=1 --branch=2.4.3 https://github.com/onqtam/doctest
RUN cmake -S doctest -B doctest/build -DDOCTEST_WITH_TESTS=OFF -DDOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF
RUN cmake --build doctest/build
RUN cmake --install doctest/build

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

# Cone FunctionalPlus
RUN git clone https://github.com/Dobiasd/FunctionalPlus

# Purposely break the tests
RUN cat FunctionalPlus/test/container_common_test.cpp | grep "container_common_test, size" -A 6
RUN sed -i 's/REQUIRE_EQ(fplus::size_of_cont(xs), 5);/REQUIRE_EQ(fplus::size_of_cont(xs), 51);/g' FunctionalPlus/test/container_common_test.cpp
RUN cat FunctionalPlus/test/container_common_test.cpp | grep "container_common_test, size" -A 6

# Build and run the tests
RUN cmake -S FunctionalPlus/test -B FunctionalPlus/build
RUN cmake --build FunctionalPlus/build -j
RUN cd FunctionalPlus/build; ctest
```

Basically, it changes

```cpp
REQUIRE_EQ(fplus::size_of_cont(xs), 5);
```

to

```cpp
REQUIRE_EQ(fplus::size_of_cont(xs), 51);
```

which should definitely break the tests, but it does not (`100% tests passed, 0 tests failed out of 417`).

I guess this might have something to do with all the recent changes regarding CMake, etc.
Can anybody (@friendlyanon @pthom @xtofl) help me out?

**Comment by pthom** [comment]
Hum, it seems to be related to the combination `ctest + doctest`:

1. if I run `container_common_test`, it fails (which is desired); and it discovers its own tests by itself:

````bash
./container_common_test
[doctest] doctest version is "2.0.0"
[doctest] run with "--help" for options
===============================================================================
/Users/pascal/dvp/OpenSource/FunctionalPlus/test/container_common_test.cpp:384:
TEST CASE:  container_common_test, size

/Users/pascal/dvp/OpenSource/FunctionalPlus/test/container_common_test.cpp:387: FATAL ERROR: REQUIRE_EQ( fplus::size_of_cont(xs), 51 ) is NOT correct!
  values: REQUIRE_EQ( 5, 51 )

===============================================================================
[doctest] test cases:     65 |     64 passed |      1 failed |      0 skipped
[doctest] assertions:    270 |    269 passed |      1 failed |
[doctest] Status: FAILURE!
````
 
2. If i run ctest, then the failure is ignored :
````
> ctest|grep "container_common_test, size"
        Start  70: container_common_test, size
 70/415 Test  #70: container_common_test, size ..................................................   Passed    0.00 sec
````

What is troubling here, is that ctest seems to use another kind of test dicovery (i.e how does it know that there is a total of 415 tests among all tests). Thus, I suspect `doctest_discover_tests`

**Comment by friendlyanon** [comment]
I dug around in gdb, looked at the CLI arguments and I came to the conclusion that doctest does not like the comma in the test case's name. Things failed successfully when I replaced `, ` with `.`.

That means that the tests with comma in their name were never run to begin with? Oops!

**Comment by Dobiasd** [comment]
> I dug around in gdb, looked at the CLI arguments and I came to the conclusion that doctest does not like the comma in the test case's name. Things failed successfully when I replaced `,` with `.`.

Thanks, I've just pushed [a branch (`test-case-names-without-comma`)](https://github.com/Dobiasd/FunctionalPlus/tree/test-case-names-without-comma) replacing `TEST_CASE("foo, bar")` with `TEST_CASE("foo - bar")`, and it works, i.e., I can make the tests fail. :+1:

---

> That means that the tests with comma in their name were never run to begin with? Oops!

Hehe, no. I can assure you, this is not the case. :slightly_smiling_face:
When I was implementing the actual functions in FunctionalPlus, I saw a lot of red (failing) tests and was fixing them. The problem of the tests not actually running must have been introduced recently. Here is a minimal example showing how the tests failed correctly a few months ago, i.e., with release `v0.2.13-p0` from Dec 6, 2020 (same doctest version, and also with `TEST_CASE("foo, bar")`):

```Dockerfile
FROM ubuntu:20.10

# Set up OS
RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y build-essential cmake git locales

# Install doctest
RUN git clone --depth=1 --branch=2.4.3 https://github.com/onqtam/doctest
RUN cmake -S doctest -B doctest/build -DDOCTEST_WITH_TESTS=OFF -DDOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF
RUN cmake --build doctest/build
RUN cmake --install doctest/build

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache

# Cone FunctionalPlus
RUN git clone https://github.com/Dobiasd/FunctionalPlus
RUN cd FunctionalPlus && git checkout 916abce0787da6c6c373d06c453a2cd684594dc2

RUN locale-gen ru_RU
RUN locale-gen ru_RU.UTF-8
RUN locale-gen el_GR
RUN locale-gen el_GR.UTF-8
RUN localedef -c -i ru_RU -f CP1251 ru_RU.CP1251
RUN localedef -c -i el_GR -f CP1253 el_GR.CP1253

# Purposely break the tests
RUN cat FunctionalPlus/test/container_common_test.cpp | grep "container_common_test, size" -A 6
RUN sed -i 's/REQUIRE_EQ(fplus::size_of_cont(xs), 5);/REQUIRE_EQ(fplus::size_of_cont(xs), 51);/g' FunctionalPlus/test/container_common_test.cpp
RUN cat FunctionalPlus/test/container_common_test.cpp | grep "container_common_test, size" -A 6

# Build and run the tests
WORKDIR /FunctionalPlus
RUN mkdir build
WORKDIR /FunctionalPlus/build
RUN cmake .. -DFPLUS_BUILD_UNITTEST=ON
RUN make -j
RUN make test
```

```
98% tests passed, 1 tests failed out of 42

Total Test time (real) =   1.67 sec

The following tests FAILED:
	  5 - container_common_test (Failed)
Errors while running CTest
make: *** [Makefile:130: test] Error 8
The command '/bin/sh -c make test' returned a non-zero code: 2
```

**Comment by friendlyanon** [comment]
Yes, but that is not using the doctest provided test discovery. Should be reported to doctest that their `--test-case` flag can't handle a name with commas.

**Comment by Dobiasd** [comment]
Thanks. :+1:
So I'll simply merge [pull/234](https://github.com/Dobiasd/FunctionalPlus/pull/234) once the CI has finished. :slightly_smiling_face:
