### ISSUE TITLE
Adding Unit Tests?

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#24]
What about adding unit tests to the project?

I have written some example tests, see here: https://github.com/offa/FunctionalPlus/tree/ut_gtest (`test` directory)

The tests are off per default at the moment – so no dependencies are needed. Only Building / running the unit tests requires gtest. To do so:

```
cd build
cmake -DUNITTEST=ON ..
make unittest
```

You can check the CI log's for the branch to see how it works.

Btw. I stumbled over #20 by writing an UT for it :+1:

**Comment by Dobiasd** [comment]
This seems like a good idea to me. The [current test coverage](https://github.com/Dobiasd/FunctionalPlus/blob/0cdf523244b5f8a4ba4f743bc81d061f12a31fba/test/tests.cpp) is far from perfect, as your [drop_if_with_idx issue](https://github.com/Dobiasd/FunctionalPlus/issues/20) showed.

Is this a task you would be interested in pursuing?

**Comment by offa** [comment]
I can't add all tests, but at least I can start – and tests will evolve. PR follows.

What's already available in my branch:

- Tests are optional (default off), so no test's means no further dependencies
- Searching for Gtest
- Some Test Cases (for filter and generate)
- make target for running the tests
- CI will build / run the available tests

**Comment by Dobiasd** [comment]
OK, great. Just merged your [commit](https://github.com/Dobiasd/FunctionalPlus/commit/afd2e17d976c7e242a4be9b85469aab93c995fc3).

**Comment by Dobiasd** [comment]
Btw, I just [moved the numeric tests over to Google Test](https://github.com/Dobiasd/FunctionalPlus/commit/dd06a5916c3118e265d3daab0545eee2a0dcca06). Does the way I did it look OK to you?

**Comment by offa** [comment]
Yes! :+1:

**Comment by offa** [comment]
More tests for generate and filter come in a minute.

**Comment by Dobiasd** [comment]
All old unit tests are now moved over to google test. Not everything is a thing of beauty, i.e. in many cases I simply used regular expressions to convert the `assert`s to `EXPECT_EQ`s, but at least it works correctly.

**Comment by offa** [comment]
@Dobiasd  is the old `tests.cpp` needed anymore?

**Comment by Dobiasd** [comment]
Not for the unit tests. It would be cool if you could remove if from our `CMakeLists.txt`.

**Comment by offa** [comment]
We can keep it as an optional target. So everyone who needs it can build / run the examples. At the moment `make test` (or equivalent: `ctest`) includes the examples, resulting in an increased build time. Maybe we also can rename it, eg. `examples.cpp`?

**Short:**

1. Rename `tests.cpp` to eg. `examples.cpp`
1. Add it as an optional make target
1. Remove it from ctest

**Comment by Dobiasd** [comment]
That sounds like an excellent plan. :)

**Comment by offa** [comment]
If that's ok, i'll take care of that (actually it's not much effort anyway).

**Comment by Dobiasd** [comment]
Of course it's ok.
