### ISSUE TITLE
error: exception handling disabled, use ‘-fexceptions’ to enable

### ISSUE THREAD

**Issue by SEEYOU20** [Dobiasd/FunctionalPlus#242]
I try to embed the frugally-deep library into ardupilot4.0 to load it. When I changed the c++ standard for compiling ardupilot code to c++14 (originally it was c++11). Some problems have occurred.
![image](https://user-images.githubusercontent.com/36726231/121801299-3bb0b180-cc69-11eb-80c4-9707f8c8b0b5.png)

**Comment by Dobiasd** [comment]
Frugally-deep uses FunctionalPlus. And FunctionalPlus uses exceptions.

It seems you have either set a compiler option like `-fno-exceptions` to disable exception handling, or it is the default in your environment.

Try using `-fexceptions` (as your error message states), it should help. :slightly_smiling_face:
