### ISSUE TITLE
Is internal_helper_carthesian_prodocut_n_idx() public API?

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#27]
Is `internal_helper_carthesian_prodocut_n_idx()` (File: `generate.h`) intended as public API? The `internal_helper` part indicates it's not. If that's the case, maybe it can be moved into an `internal` namespace?

**Comment by Dobiasd** [comment]
Thanks. Just [moved these functions](https://github.com/Dobiasd/FunctionalPlus/commit/6c747a8a4830fea7e8ffacd6df94257ba51f7755).

**Comment by offa** [comment]
Perfect :+1:
