### ISSUE TITLE
Clang 16: incompatible initializer of type (container_common_test)

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#273]
Compilation of *container_common_test.cpp* fails on Clang 16:

```
 /__w/FunctionalPlus/FunctionalPlus/test/container_common_test.cpp:664:16: error: variable 'f' with type 'const auto' has incompatible initializer of type '<overloaded function type>'
    const auto f = floor<double>;
               ^   ~~~~~~~~~~~~~
```

Full build log is available on Clang 16 PR (#274).

**Comment by Dobiasd** [comment]
Oh, interesting! :monocle_face:

`floor` is defined as follows:

```cpp
template <typename X, typename Out = int>
Out floor(X x)
```

(and only once in namespace `fplus`)

So, I guess, `overloaded function type` means there is some other function with the same name.

Would it help to change from

```cpp
const auto f = floor<double>
```

to

```cpp
const auto f = fplus::floor<double>
```

?

In case it does not help, maybe explicitly set the `Out` type like so:

```cpp
const auto f = floor<double, int>
```

Would you like to test in the [Clang 16 CI build MR](https://github.com/Dobiasd/FunctionalPlus/pull/274) or shall I?

**Comment by offa** [comment]
Adding `fplus::` seems to do the trick, PR updated :+1:

**Comment by Dobiasd** [comment]
Yay! :tada:

Thanks. :+1:
