### ISSUE TITLE
std

### ISSUE THREAD

**Issue by jhkkhtd** [Dobiasd/FunctionalPlus#3]
you use many   symbols like "std ::"  ,  adding one line that  using namespace std will be ok!

**Comment by Dobiasd** [comment]
I'm not sure if you are talking about the header files or the documentation, so I will answer both.

* header files: `using namespace std` here would mean every client automatically also has `std` imported. This can produce unneeded name colisions. So [header files should never be using any namespace](http://stackoverflow.com/questions/5849457/using-namespace-in-c-headers) to give the client the freedom to decide on their own.

* documentation: I intentionally explicitly qualified every call here, to make clear what comes from `std` and what comes from `fplus`. Some even consider [`using namespace std` bad practice](http://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice) in general. But if you use FunctionalPlus you can of course utilize `using namespace std` as you like in your code.

**Comment by jhkkhtd** [comment]
ok ,,,i think that you have teached me something, you are right   !
