### ISSUE TITLE
gcc-14 warning

### ISSUE THREAD

**Issue by fangzhou-xie** [Dobiasd/FunctionalPlus#308]
Thanks for the wonderful library.

I have an R package ([rethnicity](https://github.com/fangzhou-xie/rethnicity/issues/8)) that relies on `frugally-deep` (and hence `fplus`). I recently got an warning in the compilation that is related to the change in standard (since gcc-14) and wonder what would be the best way to get rid of this warning (warning: template-id not allowed for constructor in C++20).

The warning seems to suggest that it is the `struct array_back_insert_iterator` that has this issue.

References:
1. [C++ and ISO C++ 2017](http://eel.is/c++draft/diff.cpp17.class#2)
2. [simdjson](https://github.com/simdjson/simdjson/issues/2176)
3. [rcppsimdjson](https://github.com/eddelbuettel/rcppsimdjson/issues/91)

Thanks!

**Comment by Dobiasd** [comment]
Thanks for the nice feedback!

I'll try to fix it and will get back to you.

**Comment by Dobiasd** [comment]
Do you have a minimal example to reproduce the problem?

I tried like this

```c++
#include <fplus/fplus.hpp>
#include <iostream>
int main()
{
    std::cout << fplus::show(42) << std::endl;
}
```

```bash
g++ -std=c++20 -Wall -Wextra -pedantic -Wshadow -Werror -Weffc++ -Wconversion -Wsign-conversion -Wctor-dtor-privacy -Wreorder -Wold-style-cast -Wparentheses main.cpp
```

but don't get the warnings.

Is this the wrong `g++` version?

```bash
g++ --version
```

```
g++ (GCC) 14.1.1 20240701 (Red Hat 14.1.1-7)
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by fangzhou-xie** [comment]
Thank you very much for your reply! I double-checked and it seems I was using an old version of "fplus.hpp" which has the issue. After updating my code base using the latest version, the issue goes away. I think my issue was related to earlier issues regarding C++20 error in compilation.

Closing the issue because it is solved. Thank you for your help and sorry for the confusion.

**Comment by Dobiasd** [comment]
Ah, cool! I'm glad it's resolved.

Maybe it was fixed back then by [this commit](https://github.com/Dobiasd/FunctionalPlus/commit/ecf7072803020a9006af1a3420176a64504c55ec).
