### ISSUE TITLE
Doesn't compile with latest Visual Studio in C++23 mode

### ISSUE THREAD

**Issue by sdegutis** [Dobiasd/FunctionalPlus#309]
```
Error	C4996	'std::aligned_storage<8,8>::type': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning.	
```

**Comment by Dobiasd** [comment]
Hi @sdegutis, thanks for reporting!
The following change should fix the problem: https://github.com/Dobiasd/FunctionalPlus/pull/310

**Comment by sdegutis** [comment]
@Dobiasd cool, do you know when this change will land in vcpkg?

**Comment by Dobiasd** [comment]
I just [tagged a new release version](https://github.com/Dobiasd/FunctionalPlus/releases/tag/v0.2.25). Not sure how long it usually takes to appear in vcpkg though.

**Comment by sdegutis** [comment]
Cool thanks.
