### ISSUE TITLE
enable clang in travis CI

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#39]
Currently our travis ci configuration uses 4 different g++ versions for the tests. I think it would be cool if it could use at least one version of clang additionally.
@offa: Is this something you could have a look at?

**Comment by offa** [comment]
Unfortunately clang apt repositories are down (http://llvm.org/apt/). And according to their mailing list there isn't a replacement ready yet.

**Comment by Dobiasd** [comment]
Ah OK, thank you. So I guess we just wait for them. :)

**Comment by Dobiasd** [comment]
I just noticed that [tiny-cnn](https://github.com/nyanp/tiny-cnn) currently has clang enabled in [its travis ci build](https://travis-ci.org/nyanp/tiny-cnn), and it seems to work. Does the approach used there make sense for our project too?

**Comment by offa** [comment]
It's an old version of clang (3.4). If that's enough, we can try it. 

Good news anyway: Clang Repositories are up again. As travis re-enables them (https://github.com/travis-ci/travis-ci/issues/6217) we can add a more recent version of clang.
