### ISSUE TITLE
scan_right_1 API doc

### ISSUE THREAD

**Issue by mu-chan** [Dobiasd/FunctionalPlus#46]
Thank you for creating FunctionalPlus! 
I was interested in it, and reading code and made memo/summary for my use, then found small error in API doc  for scan_right_1
Probably, result [1,3,6] is remain of copy&paste from scan_left_1, isn't it?
I get == [6,5,3] as expected.

quote   container_common.hpp line:522
---------------------------------------------------------------------------
// API search type: scan_right_1 : (((a, a) -> a), [a]) -> [a]
// scan_right_1((+), [1, 2, 3]) == [1, 3, 6]
// Takes the last two items of the list and applies the function,
// then it takes the third item from the end and the result, and so on.
// It returns the list of inntermediate and final results.
template <typename F, typename ContainerIn,
    typename Acc = typename ContainerIn::value_type,
    typename ContainerOut = typename same_cont_new_t<ContainerIn, Acc>::type>
ContainerOut scan_right_1(F f, const ContainerIn& xs)
{
    return reverse(scan_left_1(flip(f), reverse(xs)));
}
---------------------------------------------------------------------------

**Comment by Dobiasd** [comment]
Thank you very much. [It is fixed now](https://github.com/Dobiasd/FunctionalPlus/commit/065e237b2b8d95a8008039b0f35b296690c4e54c).
