### ISSUE TITLE
Room for performance improvement in `split_by`

### ISSUE THREAD

**Issue by ztdwu** [Dobiasd/FunctionalPlus#5]
The performance of `split_by` can be improved by using a more efficient tokenizing algorithm as written here (not by me) http://tcbrindle.github.io/posts/a-quicker-study-on-tokenising. I've included an inlined version of the algorithm in the test program below. Here are the execution times of splitting a short string 5,000,000 times, compiled with `-O3` on `clang 3.7` on x86_64 Linux 4.3:

```
Time taken: 19.8554 (fplus::split_words)
Time taken: 2.02921 (improved version)
```

```c++
#include <algorithm>
#include <chrono>
#include <iostream>
#include <vector>
#include "fplus.h"

// Slightly modified code based on http://tcbrindle.github.io/posts/a-quicker-study-on-tokenising/
template <typename Str, typename Container = std::vector<std::string>>
Container tokenize(const Str &str, const char delim = ' ') {
    Container result;
    auto inserter = std::inserter(result, std::begin(result));

    auto token_start = std::begin(str);
    while (token_start != std::end(str) && *token_start) {
        const auto token_end = std::find(token_start, std::end(str), delim);
        if (token_start != token_end) {
            *inserter = { token_start, token_end };
        }
        if (token_end == std::end(str)) break;
        token_start = std::next(token_end);
    }
    return result;
}


int main() {
    using namespace std::chrono;

    auto words = std::string{ "a bb ccc dddd eeeee ffffff ggggggg hhhhhhhhh" };

    const auto start_time = high_resolution_clock::now();
    for (auto _ = 0; _ < 5000000; _++) {
        // auto tokens = fplus::split_words(words);
        auto tokens = tokenize(words);
    }
    const auto elapsed = high_resolution_clock::now() - start_time;
    std::cout << "Time taken: " << duration_cast<duration<double>>(elapsed).count() << std::endl;
}
```

**Comment by Dobiasd** [comment]
Wow, that is very cool improvement. Thank you very much!

`split_words` internally uses the more general [`split_by`](https://github.com/Dobiasd/FunctionalPlus/blob/c2d00f66eb736fa04249d8c1afc74dcedd41d305/include/fplus/split.h#L106). Are you interested in reimplementing `split_by` using this algorithm and submitting a pull request? Otherwise please let me know, I will then see what I can do. :)

**Comment by ztdwu** [comment]
Sounds good. A little busy lately so I'll probably submit the PR in a few days, if that works for you.

**Comment by Dobiasd** [comment]
Yes, sure. Take your time.
