### ISSUE TITLE
travis build, Could not find compiler set in environment variable CC: clang-3.7

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#50]
https://travis-ci.org/Dobiasd/FunctionalPlus/jobs/166689095
@offa: Any idea what is wrong?

**Comment by offa** [comment]
It seems clang3.7 wasn't installed correctly:

```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install clang-3.7
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 87 not upgraded.
```

Since the builds before didn't fail by this, possible it's just an temporary issue.

**Comment by offa** [comment]
@Dobiasd I've pushed a branch and this time Gcc4.9 failed:

`curl: (7) Failed to connect to llvm.org port 80: Connection timed out`

Clang 3.7 was ok that time.

**Comment by Dobiasd** [comment]
Ah, OK. I guess it will just start to work again with some future commit, so I'll stop worrying. Thank you!
