### ISSUE TITLE
no member named 'gets' in the global namespace on Clang

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#59]
When compiling with C++14 the [build fails on some Clang versions](https://travis-ci.org/Dobiasd/FunctionalPlus/builds/184995090).

[SO says](http://stackoverflow.com/a/24342365/1866775) one should use `-stdlib=libc++`. Do I simply have to remove `libc++-dev` in `.travis.yml` or replace it with something?

@offa It would be totally cool if you could help me out again. :D

**Comment by offa** [comment]
all right, i'm on it.

**Comment by Dobiasd** [comment]
Thank you very much. :+1:
