### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by offa** [Dobiasd/FunctionalPlus#62]
Contribution guidelines (see #58; starting at https://github.com/Dobiasd/FunctionalPlus/issues/58#issuecomment-268033300).

**Comment by Dobiasd** [comment]
OK, just pushed an [updated version of `CONTRIBUTING.md`](https://github.com/Dobiasd/FunctionalPlus/blob/b38d2f57270431938153d6dddf7f63c0ae0b18f3/CONTRIBUTING.md). What do you think about it? You are also welcome to edit it on your own, if this speeds up the process.

**Comment by offa** [comment]
@Dobiasd I think we can close here; file looks good so far.
