### ISSUE TITLE
error: 'fwd' has not been declared (gcc version 4.9.2)

### ISSUE THREAD

**Issue by Kvaz1r** [Dobiasd/FunctionalPlus#68]
When I compile followinf code from [usage-examples](https://github.com/Dobiasd/FunctionalPlus#comparison-with-range-v3):

```
#include <fplus/fplus.hpp>
#include <iostream>

int main()
{
using namespace fplus;
const auto result_fplus = fwd::apply(
    numbers(0, 15000000)
    , fwd::transform(times_3)
    , fwd::drop_if(is_odd)
    , fwd::transform(as_string_length)
    , fwd::sum());
}
```

get error:

> error: 'fwd' has not been declared
>  const auto result_fplus = fwd::apply(
> ...

is it possible rewrite it without updated of the compiler?

**Comment by Dobiasd** [comment]
In [fplus.hpp](https://github.com/Dobiasd/FunctionalPlus/blob/master/include/fplus/fplus.hpp) there is the following code:

    #if __cplusplus >= 201402L || _MSC_VER >= 1900
        #include <fplus/fwd.hpp>
    #endif

Perhaps your gcc version (4.9.2) does not define the needed preprocessor flag. Please try including `fwd.hpp` explicitly, like so:

    #include <fplus/fplus.hpp>
    #include <fplus/fwd.hpp>
    #include <iostream>

    const auto times_3 = [](int i){return 3 * i;};
    const auto is_odd_int = [](int i){return i % 2 == 0;};
    const auto as_string_length = [](int i){return std::to_string(i).size();};

    int main()
    {
        using namespace fplus;
        const auto result_fplus = fwd::apply(
            numbers(0, 15000000)
            , fwd::transform(times_3)
            , fwd::drop_if(is_odd_int)
            , fwd::transform(as_string_length)
            , fwd::sum());
    }

**Comment by Kvaz1r** [comment]
Thanks, explicit inclusion of the header solved the problem.
