### ISSUE TITLE
GCC 6 warnings in variadic min_on and max_on

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#69]
[GCC 6 now warns differently about unused but set variables which breaks the travis builds.](https://travis-ci.org/Dobiasd/FunctionalPlus/jobs/236447148)
@pmalek, since you initially contributed [this piece](https://github.com/Dobiasd/FunctionalPlus/pull/30/commits/5e11e9b626a8e9d77b782983c03dfaceeb15a7d6) I was wondering if you have an idea on how to fix it?

**Comment by offa** [comment]
Interesting, I do not get those warnings with GCC 6(.3.1) on my system.

Generally, if it's unused, why not just remove it?

**Comment by Dobiasd** [comment]
Because it is used. :D

**Comment by offa** [comment]
Well, that complicates the issue …

**Comment by offa** [comment]
I guess in this part:

```cpp
      (void)std::initializer_list<int>{
          ((v_trans = f(v), v_trans < result_trans)
               ? (result = static_cast<rettype>(v), result_trans = v_trans, 0)
               : 0)...};
```

The code is optimized somehow so `v_trans` and `result_trans` aren't actually used.

**Comment by offa** [comment]
I'll check out, if a simple cast to void can workaround this.

**Comment by Dobiasd** [comment]
Cool.
I am currently unable to reproduce the problem on [godbolt.org](https://godbolt.org/g/0qjwaq).

**Comment by offa** [comment]
> I'll check out, if a simple cast to void can workaround this.

It can't (why!?)

**Comment by Dobiasd** [comment]
I guess i'll just `#pragma GCC diagnostic ignored "-Wunused-but-set-variable"` it away. What do you think?

**Comment by offa** [comment]
This affects all compilers and incl. all versions of Gcc6, even though only one (?) Gcc 6 version is actually broken. Let's make sure before, that there's no real and hidden issue behind this.

**Comment by offa** [comment]
[One thing I'm not sure](https://github.com/Dobiasd/FunctionalPlus/blob/master/include/fplus/numeric.hpp#L296):

```cpp
using f_rettype = decltype(f(first));
```
Does this return the correct type, or the type of `f`? Something like this would be needed for the latter:

```cpp
using f_rettype = typename std::result_of<F(decltype(first))>::type;
```

**Comment by Dobiasd** [comment]
Looks reasonable. Perhaps this fix additionally would prevent the warning? Can you try it out with a PR?

**Comment by offa** [comment]
I'll open a PR to this, but it won't fix the problem (already tested on travis).

**Comment by offa** [comment]
Gcc7 has this problem too: https://travis-ci.org/offa/FunctionalPlus/jobs/236900730#L415

At least on travis.

**Comment by offa** [comment]
```cpp
      if( &v_trans == &result_trans) {  }
```
Seems to work.

**Comment by Dobiasd** [comment]
With GCC 7 I can recreate it: https://godbolt.org/g/SgcpkW

**Comment by Dobiasd** [comment]
I'm not sure if it can prevent any optimizations. At least it not as ugly as the `pragma` workaround.

**Comment by offa** [comment]
Seems also ok:

```cpp
template<class T> inline void unused(T&&) { }

…

unused(result_trans);
 unused(v_trans);
```

**Comment by Dobiasd** [comment]
This looks a bit better to me, because it feels more like it would not produce run-time overhead. I would say https://www.youtube.com/watch?v=vCadcBR95oU

**Comment by offa** [comment]
On the way (rebase and typo fixed before).

**Comment by Dobiasd** [comment]
Thanks once again. :)
