### ISSUE TITLE
std::initializer_list

### ISSUE THREAD

**Issue by jchia** [Dobiasd/FunctionalPlus#7]
It seems that at least some functions don't work with initializer_list. Is it possible to make make them work? For example, this doesn't compile:

```
void foo(initializer_list<int> const& x) {
    fplus::transform([](int i){ return i + 1;}, x);
}
```

**Comment by Dobiasd** [comment]
Very good observation. I had not tried this out yet. fplus::transform is declared like this:

    template <typename F, typename ContainerIn,
        typename ContainerOut = typename same_cont_new_t_from_unary_f<
            ContainerIn, F>::type>
    ContainerOut transform(F f, const ContainerIn& xs)

So it needs a concrete container as an output.

In case of `transform` you could [use `transform_convert` to set an output container](https://github.com/Dobiasd/FunctionalPlus/commit/7e09d0ec0facb15cb66f839979179e2170992992#diff-0b8580e58122b92a0bbfed41193065a2R584).
But for most functions it probably is easier to [convert to a std::vector before making the call](https://github.com/Dobiasd/FunctionalPlus/commit/7e09d0ec0facb15cb66f839979179e2170992992#diff-0b8580e58122b92a0bbfed41193065a2R583).
