### ISSUE TITLE
Taking advantage of move-semantics.

### ISSUE THREAD

**Issue by TurpentineDistillery** [Dobiasd/FunctionalPlus#73]
e.g. let's look at `keep_if`

```c++
template <typename Pred, typename Container>
Container keep_if(Pred pred, const Container& xs)
{
    internal::check_unary_predicate_for_container<Pred, Container>();
    Container result;
    auto it = internal::get_back_inserter<Container>(result);
    std::copy_if(std::begin(xs), std::end(xs), it, pred);
    return result;
}
```

It looks to me it would be better implemented as

```c++
template <typename Pred, typename Container>
Container keep_if(Pred pred, Container xs)
{
    // erase-remove elements from xs, per predicate
    return xs;
}
```

This way if the container is passed as rvalue, as would most likely be the case, then we have no copy-overhead: `xs` is passed by-move, edited in-place, and returned by-move.

This is not just applicable to `keep_if`, but the family of functions where input and output types are the same, and the input is likely to be passed as rvalue, and the type is potentially heavy to copy.

**Comment by Dobiasd** [comment]
Thank you for contributing this good observation.

I think it depends on the type of container. In case of an `std::list` it would make sense to remove elements in-place, since every remove operation is O(1). But for an `std::vector` removing an element is O(n), so the overall time complexity of `keep_if<F, std::vector<T>>` would become O(n²). The difference in execution time between the following two examples is huge:

[keep_if_test.cpp](https://gist.github.com/Dobiasd/b37dfe0400013a5634a548c45e1a28c6)

[keep_if_in_place_test.cpp](https://gist.github.com/Dobiasd/76f543144f21951d94a2e87fdae4f738)

For things like `sort` on the other hand, it could be a good idea to use the approach you suggest by default.

**Comment by Dobiasd** [comment]
OK, I admin my implementation of `keep_if_in_place` from above is a bit naive. With storing an iterator to the most left "hole" and moving manually, one could actually achieve overall O(n).

**Comment by Dobiasd** [comment]
I guess you were thinking about something like that: https://gist.github.com/Dobiasd/e4823d696f071c6ea6270055bed5c574

This indeed seems to be quite a good approach to me, of course also for `std::vector`.

**Comment by Dobiasd** [comment]
We could even use `std::copy_if` to operate in-place (`keep_if_in_place_3`), I guess: https://gist.github.com/Dobiasd/ca4ac11e285d217b151da629e1b3f53a

But this one probably will not move the elements inside the container like `keep_if_in_place_2` does.

The only downside I can think of at the moment is the following scenario:
We call our new in-place keep_if with an l-value container and only very few of the elements actually fulfill the predicate. In that case all elements will be copied once, which would be avoided by the current version taking a ref-to-const.

**Comment by TurpentineDistillery** [comment]
Filtering can be done in O(n) for all standard containers. See https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom

I see your point about the use-case where we have a large container with a few satisfying elements. The dual of this use-case is where you have many satisfying elements and you'd like to avoid copying. It's a trade-off. Having both overloads would probably me most "correct" approach, but I don't like it either for the reasons you mentioned.

**Comment by TurpentineDistillery** [comment]
Another approach would be to take container as forwarding-reference `Container&&` internally type-dispatch to two implementations, one taking `Container&` and another `Container&&`

**Comment by Dobiasd** [comment]
This sounds good. Are you interested in exploring this idea further implementation-wise? It will be interesting to see if one runs into any problems with the type system, for example when binding arguments like in `fplus::fwd`.

**Comment by TurpentineDistillery** [comment]
I may be interested, but unfortunately am unable to contribute in the near future; also I'm limited to working with c++11 only.

**Comment by Dobiasd** [comment]
OK, no problem. I will see if I can conduct some tests in the next few days.

**Comment by Dobiasd** [comment]
It seems possible and works for `keep_if` like this:

    template <typename Pred, typename Container,
        typename = typename std::enable_if<
            std::is_nothrow_assignable<
                typename Container::value_type,
                typename Container::value_type>::value>::type>
    Container keep_if(Pred pred, Container&& xs)
    {
        xs.erase(std::remove_if(
            std::begin(xs), std::end(xs), logical_not(pred)), std::end(xs));
        return xs;
    }

    template <typename Pred, typename Container>
    Container keep_if(Pred pred, const Container& xs)
    {
        internal::check_unary_predicate_for_container<Pred, Container>();
        Container result;
        auto it = internal::get_back_inserter<Container>(result);
        std::copy_if(std::begin(xs), std::end(xs), it, pred);
        return result;
    }

    } // namespace internal

    // API search type: keep_if : ((a -> Bool), [a]) -> [a]
    // fwd bind count: 1
    // Keep the elements of a sequence fulfilling a predicate.
    // keep_if(is_even, [1, 2, 3, 2, 4, 5]) == [2, 2, 4]
    // Also known as filter.
    template <typename Pred, typename Container,
        typename Out = typename std::remove_reference<Container>::type>
    Out keep_if(Pred pred, Container&& xs)
    {
        return internal::keep_if(pred, std::forward<decltype(xs)>(xs));
    }

Candidate functions for this kind of optimization probably are all functions that return the same container type as they take as input. Probably most of the following:

    include/fplus/container_common.hpp:Container get_segment
    include/fplus/container_common.hpp:Container set_segment
    include/fplus/container_common.hpp:Container remove_segment
    include/fplus/container_common.hpp:Container insert_at(std::size_t idx_begin,
    include/fplus/container_common.hpp:Container replace_segment(std::size_t idx_begin,
    include/fplus/container_common.hpp:Container reverse(const Container& xs)
    include/fplus/container_common.hpp:Container take(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container take_exact(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container take_cyclic(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container drop(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container take_last(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container drop_last(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container drop_exact(std::size_t amount, const Container& xs)
    include/fplus/container_common.hpp:Container take_while(UnaryPredicate pred, const Container& xs)
    include/fplus/container_common.hpp:Container drop_while(UnaryPredicate pred, const Container& xs)
    include/fplus/container_common.hpp:Container append_elem(const Container& xs, const T& y)
    include/fplus/container_common.hpp:Container prepend_elem(const Container& xs, const T& y)
    include/fplus/container_common.hpp:Container append(const Container& xs, const Container& ys)
    include/fplus/container_common.hpp:Container interweave(const Container& xs, const Container& ys)
    include/fplus/container_common.hpp:Container sort_by(Compare comp, const Container& xs)
    include/fplus/container_common.hpp:Container sort_on(F f, const Container& xs)
    include/fplus/container_common.hpp:Container sort(const Container& xs)
    include/fplus/container_common.hpp:Container stable_sort_by(Compare comp, const Container& xs)
    include/fplus/container_common.hpp:Container stable_sort_on(F f, const Container& xs)
    include/fplus/container_common.hpp:Container stable_sort(const Container& xs)
    include/fplus/container_common.hpp:Container partial_sort_by(Compare comp, std::size_t count, const Container& xs)
    include/fplus/container_common.hpp:Container partial_sort_on(F f, std::size_t count, const Container& xs)
    include/fplus/container_common.hpp:Container partial_sort(std::size_t count, const Container& xs)
    include/fplus/container_common.hpp:Container unique_by(BinaryPredicate p, const Container& xs)
    include/fplus/container_common.hpp:Container unique_on(F f, const Container& xs)
    include/fplus/container_common.hpp:Container unique(const Container& xs)
    include/fplus/container_common.hpp:Container intersperse(const X& value, const Container& xs)
    include/fplus/container_common.hpp:Container nub_by(BinaryPredicate p, const Container& xs)
    include/fplus/container_common.hpp:Container nub_on(F f, const Container& xs)
    include/fplus/container_common.hpp:Container nub(const Container& xs)
    include/fplus/container_common.hpp:Container init(const Container& xs)
    include/fplus/container_common.hpp:Container tail(const Container& xs)
    include/fplus/container_common.hpp:Container lexicographical_sort(const Container& xs)
    include/fplus/extrapolate.hpp:Container extrapolate_replicate(std::size_t count_begin, std::size_t count_end,
    include/fplus/extrapolate.hpp:Container extrapolate_wrap(std::size_t count_begin, std::size_t count_end,
    include/fplus/filter.hpp:Container keep_if(Pred pred, Container&& xs)
    include/fplus/filter.hpp:Container keep_if(Pred pred, const Container& xs)
    include/fplus/filter.hpp:Container drop_if(Pred pred, const Container& xs)
    include/fplus/filter.hpp:Container without(T elem, const Container& xs)
    include/fplus/filter.hpp:Container without_any(const ContainerElems& elems, const Container& xs)
    include/fplus/filter.hpp:Container keep_if_with_idx(Pred pred, const Container& xs)
    include/fplus/filter.hpp:Container drop_if_with_idx(Pred pred, const Container& xs)
    include/fplus/filter.hpp:Container keep_by_idx(UnaryPredicate pred, const Container& xs)
    include/fplus/filter.hpp:Container drop_by_idx(UnaryPredicate pred, const Container& xs)
    include/fplus/filter.hpp:Container keep_idxs(const ContainerIdxs& idxs_to_keep, const Container& xs)
    include/fplus/filter.hpp:Container drop_idxs(const ContainerIdxs& idxs_to_drop, const Container& xs)
    include/fplus/filter.hpp:Container drop_idx(std::size_t idx, const Container& xs)
    include/fplus/filter.hpp:Container trim_left(const T& x, const Container& xs)
    include/fplus/filter.hpp:Container trim_token_left(const Container& token, const Container& xs)
    include/fplus/filter.hpp:Container trim_right_by(UnaryPredicate p, const Container& xs)
    include/fplus/filter.hpp:Container trim_right(const T& x, const Container& xs)
    include/fplus/filter.hpp:Container trim_token_right(const Container& token, const Container& xs)
    include/fplus/filter.hpp:Container trim_by(UnaryPredicate p, const Container& xs)
    include/fplus/filter.hpp:Container trim(const T& x, const Container& xs)
    include/fplus/filter.hpp:Container trim_token(const Container& token, const Container& xs)
    include/fplus/filter.hpp:Container adjacent_keep_snd_if(BinaryPredicate p, const Container& xs)
    include/fplus/filter.hpp:Container adjacent_drop_fst_if(BinaryPredicate p, const Container& xs)
    include/fplus/filter.hpp:Container adjacent_drop_snd_if(BinaryPredicate p, const Container& xs)
    include/fplus/filter.hpp:Container adjacent_keep_fst_if(BinaryPredicate p, const Container& xs)
    include/fplus/generate.hpp:Container repeat(std::size_t n, const Container& xs)
    include/fplus/generate.hpp:Container adjacent_difference(const Container& xs)
    include/fplus/generate.hpp:Container rotate_left(const Container& xs)
    include/fplus/generate.hpp:Container rotate_right(const Container& xs)
    include/fplus/generate.hpp:Container fill_left(const T& x, std::size_t min_size, const Container& xs)
    include/fplus/generate.hpp:Container fill_right(const T& x, std::size_t min_size, const Container& xs)
    include/fplus/numeric.hpp:Container normalize_min_max(
    include/fplus/numeric.hpp:Container normalize_mean_stddev(
    include/fplus/numeric.hpp:Container standardize(const Container& xs)
    include/fplus/replace.hpp:Container replace_if(UnaryPredicate p,
    include/fplus/replace.hpp:Container replace_elem_at_idx(std::size_t idx, const T& dest, const Container& xs)
    include/fplus/replace.hpp:Container replace_elems(const T& source, const T& dest, const Container& xs)
    include/fplus/replace.hpp:Container replace_tokens
    include/fplus/split.hpp:Container insert_at_idx(std::size_t idx, const T& x, const Container& xs)
    include/fplus/split.hpp:Container stride(std::size_t step, const Container& xs)
    include/fplus/split.hpp:Container winsorize(double trim_ratio, const Container& xs)
    include/fplus/transform.hpp:Container replicate_elems(std::size_t n, const Container& xs)
    include/fplus/transform.hpp:Container transpose(const Container& rows)
    include/fplus/transform.hpp:Container shuffle(std::uint_fast32_t seed, const Container& xs)
    include/fplus/transform.hpp:Container sample(std::uint_fast32_t seed, std::size_t n, const Container& xs)
    include/fplus/transform.hpp:Container random_elements(
    include/fplus/transform.hpp:Container keep_if_parallelly(Pred pred, const Container& xs)

Quite some work ahead :D

**Comment by Dobiasd** [comment]
Shoot! There is a problem on MSVC and GCC < 6.3 with this approach: https://stackoverflow.com/questions/44542512/dispatching-r-values-and-l-values-differently-and-using-sfinae-to-disable-one-op

**Comment by TurpentineDistillery** [comment]
I was thinking this could happen, but I was thinking of `std::set` where erase-remove idiom won't work https://stackoverflow.com/questions/11141651

One possibility is to specialize the handling of std::map and std::set to drop the elements the "old school" way - just iterate over the container and erase at iterator per predicate, or use the lvalue-based implementation for these.

**Comment by TurpentineDistillery** [comment]
Also you never need to write `return std::move(...)` as far as I understand - the standard dictates that if  `return` can theoretically return as rvalue, it shall, without having to be told explicitly (that's the gist of it)

**Comment by Dobiasd** [comment]
Using the l-value implementation for `std::map` is exactly what I am intending.
The `value_type` of an `std::map` is `std::pair<const Key, Val>`. And in my SO question I am trying to dispatch these things into the l-value version, but in a more general way than simply specializing the function for `std::map`. Everything that can not be assigned (as the implementation of `copy_if` requires) should not land there. The pairs inside a map are only one of many possible examples for this. But I guess I have to settle for some kind of workaround since the standard / compilers had a [bug](https://stackoverflow.com/questions/44538913/stdis-assignable-and-stdpairconst-t-u) regarding `std::is_assignable` in combination with `std::pairs`.

---

I used to think the same thing about `std::move` but in our case `xs` seems to not be eligible for copy elision, see [this answer](https://stackoverflow.com/a/14857144/1866775).

**Comment by Dobiasd** [comment]
So, many functions now support r-value references. It also works for [composition and forward application](https://github.com/Dobiasd/FunctionalPlus/pull/76/commits/95dfd8bef676df9081d1551dc8a1ce2b5e7de140), which is important, I think.
There still are some not so common functions in fplus that could support move semantics but do not do it yet. I will perhaps extend them in the future. However the large majority of use-cases already is covered. Since this did not break the API, a lot of FunctionalPlus code will become faster with this update right out-of-the-box. :-)

@TurpentineDistillery Thanks again for this suggestion. After some initial problems the implementation went smoothly, I learned a lot along the way and the quality (i.e. performance in that case) of the library was improved substantially.

**Comment by TurpentineDistillery** [comment]
That was a super quick fix, considering the scope.
Also, thanks for the explanation about return-by-move caveats!
