### ISSUE TITLE
using std::array

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#75]
The following code does not compile.

    #include <fplus/fplus.hpp>
    int main()
    {
        std::array<int, 3> xs = {0,1,2};
        fplus::transform(fplus::square<int>, xs);
    }

`fplus::transform` (and some other functions) could deduce the length of the returned sequence at compile time and thus support `std::array` in theory.

I'm thinking about adding this functionality, but I'm still in the process of gathering ideas around this topic. Any thoughts? :)

**Comment by xtofl** [comment]
`std::array` can be treated the same as `std::vector` - it has the same free functions implemented to iterate over it (`std::begin/end`).  Odd that it doesn't already compile out of the box.

**Comment by Dobiasd** [comment]
As a source container `std::array` is no problem, but as a output container it is. Currently I use the returned iterator of [`internal::get_back_inserter`](https://github.com/Dobiasd/FunctionalPlus/blob/87649dc17c1667334874a377e7eebabd144bfee3/include/fplus/container_common.hpp#L90) to fill the output containers.

For `std::array` `internal::get_back_inserter` would need an overload, but simply letting it return `std::begin(xs)` can become dangerous, because every function manually has to make sure to not write out of the array bounds.

Functions like [`overlapping_pairs`](https://github.com/Dobiasd/FunctionalPlus/blob/87649dc17c1667334874a377e7eebabd144bfee3/include/fplus/pairs.hpp#L343) would need to create and return an `std::array<T, N+1>` in case of an `std::array<T, N>` as input. It somewhat reminds me of dependent types in Idris. :D

**Comment by Dobiasd** [comment]
[The solution](https://github.com/Dobiasd/FunctionalPlus/commit/20fda298dc707ca89f7ce9445375eea9729fbb1d) turned out to be quite nice in my opinion. :)

The new `same_cont_new_t` only works for arrays if a `size_offset` is passed explicitly. This way one can enable `std::array` support for appropriate functions (i.e. functions where the size of the output sequence can be deduced by the size of the input sequence, e.g. `transform`, `transform_inner`, `scan_left`, `scan_left_1`, `overlapping_pairs`, `swap_pairs_elems` etc.).

And one can not accidentally write a function that supports `std::array` from the point of view of the type system. I think this is important, because I do not want to see surprising memory corruptions occurring at runtime because a function wrote behind the array bounds.

`fplus::internal::array_back_insert_iterator` is there in order to make us able to use arrays as destination containers (again, only where explicitly enabled) like sequences that support `::push_back`. Internally an assertion in the destructor of this iterator makes sure the destination array is not only filled partially before returned.
