### ISSUE TITLE
transform_pair not working with std::function

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#88]
The following code does not compile any more. I guess it has something to do with PR #87.

```cpp
const std::function<int(int)> double_int = [](int x) -> int
{
    return 2 * x;
};
typedef std::pair<int, int> IntPair;
fplus::transform_pair(double_int, double_int, IntPair({2,3}));
```

@theodelrieu, could you please have a look at it?

**Comment by theodelrieu** [comment]
This is related to `void_t`. I used the cppreference one (supposedly compatible with C++14, but GCC7 seems unhappy with it)

**Comment by Dobiasd** [comment]
Thanks a lot for this very quick fix.
