### ISSUE TITLE
keep_if(compose(square, is_greater_or_equal_than), xs) does not compile any more

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#93]
The following code compiled some time ago but does not compile any more with the latest version.

```cpp
int main()
{
    fplus::keep_if(
        fplus::compose(
            fplus::square<int>,
            fplus::is_greater_or_equal_than(3)),
        std::vector<int>());
}
```

@theodelrieu, could you please have a look at it?

**Comment by theodelrieu** [comment]
I'll take a look tomorrow morning.

**Comment by Dobiasd** [comment]
The collatz example from the `README.md` also does not compile any more. Since it also uses `compose` I guess this could be related.

```cpp
    typedef std::list<int> Ints;

    // [1, 2, 3 ... 29]
    auto xs = fplus::numbers<int>(1, 30);

    // A function that does [1, 2, 3, 4, 5] -> "[1 => 2 => 3 => 4 => 5]"
    auto show_ints = fplus::bind_1st_of_2(fplus::show_cont_with<Ints>, " => ");

    // A composed function that calculates a Collatz sequence and shows it.
    auto show_collats_seq = fplus::compose(collatz_seq, show_ints);

    // Associate the numbers with the string representation of their sequences.
    auto collatz_dict = fplus::create_map_with(show_collats_seq, xs);

    // Print some of the sequences.
    std::cout << collatz_dict[13] << std::endl;
    std::cout << collatz_dict[17] << std::endl;
```

**Comment by Dobiasd** [comment]
I [just added](https://github.com/Dobiasd/FunctionalPlus/commit/8d57198ab5937c6a884140008e4f02644a9768fa) all examples from our `README.md` to the tests.

They now work since [I temporarily replaced the `compose` with a lambda](https://github.com/Dobiasd/FunctionalPlus/blob/8d57198ab5937c6a884140008e4f02644a9768fa/test/readme_examples_test.cpp#L124).

**Comment by theodelrieu** [comment]
I'm on it.

Also I realized I forgot something very simple... I should have targeted a feature branch, not master. Every function that uses `function_traits` directly will fail to compile when given function I converted...

I think it would be great to revert my changes on master, and cherry pick the commits on a `feature/generic_lambdas` branch.

**Comment by Dobiasd** [comment]
I fear I could create quite a mess with this. Is it OK for you if I add you as a collaborator to this repo so you can help me out?

**Comment by theodelrieu** [comment]
Sure. I found the problem, it's related to `internal::check_arity`, removing them in `container_common.hpp` solve this issue.

But the real fix is to put my commits in a branch and wait for the full conversion.

**Comment by theodelrieu** [comment]
I'll first cherry pick, then revert the merge commits in master.

Sorry about this, quite a rookie mistake :|

**Comment by theodelrieu** [comment]
I reverted the dreadful commits, this should solve this issue. I'll open another PR right after.

In the end, I don't need the collaborator rights to do this. So feel free to downgrade me :)

**Comment by Dobiasd** [comment]
Don't worry about it. I also could have prevented it with better test coverage.

**Comment by Dobiasd** [comment]
This was fixed with [PR94](https://github.com/Dobiasd/FunctionalPlus/pull/94).
