### ISSUE TITLE
using libc++ on travis

### ISSUE THREAD

**Issue by Dobiasd** [Dobiasd/FunctionalPlus#97]
To consolidate the problem I open this new issue.

Situation: We would like to use recent versions of libc++ on Travis (Ubuntu Trusty).
The default version provided with `sudo apt install libc++-dev` is `svn199600` (`_LIBCPP_VERSION` is defined as `1101`).

My attempts to learn about how to do it on SO ([1](https://stackoverflow.com/questions/45946131/using-different-libc-versions-on-travis-for-clang), [2](https://stackoverflow.com/questions/46232955/how-to-install-libc-3-9-on-ubuntu-trusty-without-building-from-source)) were not successful yet.

**Comment by Dobiasd** [comment]
I just found out [range-v3](https://travis-ci.org/ericniebler/range-v3) uses libc++ on travis. It is installed there with [this script](https://github.com/ericniebler/range-v3/blob/master/install_libcxx.sh). Perhaps we can learn from it and do something similar?

**Comment by theodelrieu** [comment]
Great idea, if that works for them, it will most likely work for us!

**Comment by Dobiasd** [comment]
I made some progress on the [travis_libcxx branch](https://github.com/Dobiasd/FunctionalPlus/tree/travis_libcxx).

First, it looks like we really have to build libc++ from source if we want to use it on travis/trusty. Since range-v3 also does it, I simply copied `install_libcxx.sh` from there.

In order to run it, one needs cmake 3.4.3 or higher installed. The default version in Trusty is below this and the [3rd-party repo](https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x) for cmake I found only goes up to 3.2.2.2 for trusty. So I also had to build cmake from source.

This makes our `travis.yml` more complex, and it increases the build times on Travis and the length of the logs there.

But at least [it works](https://travis-ci.org/Dobiasd/FunctionalPlus/builds/276190818). I added a `show_version.cpp` and it shows libc++ is now on version `3900` (`_LIBCPP_VERSION`) in the clang builds.

Should we accept the disadvantages mentioned above? I would like to hear the opinion of you guys about it.

**Comment by theodelrieu** [comment]
Isn't there a way to download pre-built packages? We could host the binaries somewhere and simply retrieve them with a wget or something like this.

**Comment by Dobiasd** [comment]
Haha, I just found out trusty provides a `cmake3` package which holds version 3.5.1. So there is no need to build cmake from source. The build times for the clang tests are now down from about 10 minutes to about 4 minutes. Only libc++ is built from source, and that does not take terribly long.

**Comment by theodelrieu** [comment]
Great, that's acceptable

**Comment by Dobiasd** [comment]
OK, [merged](https://github.com/Dobiasd/FunctionalPlus/pull/98). :)
